import * as T from './vendor/three.module.js';
import {GLTFLoader} from './vendor/loaders/GLTFLoader.js';
// Original interactive 3D stage. Rendered movie scenes lead into manipulable props.
export class StoryStage {
 constructor(host,onPick){this.host=host;this.pick=onPick;this.renderer=new T.WebGLRenderer({antialias:true,alpha:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.25;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;host.append(this.renderer.domElement);this.scene=new T.Scene();this.camera=new T.PerspectiveCamera(39,1,.1,60);this.camera.position.set(0,6.7,10.4);this.camera.lookAt(0,.35,0);this.root=new T.Group();this.scene.add(this.root);this.scene.add(new T.HemisphereLight(0xf6f7db,0x385950,2.4));const key=new T.DirectionalLight(0xffe6b8,3.5);key.position.set(-5,9,7);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-7;key.shadow.camera.right=7;key.shadow.camera.top=7;key.shadow.camera.bottom=-7;key.shadow.normalBias=.02;this.scene.add(key);const fill=new T.DirectionalLight(0xcee7e1,1);fill.position.set(5,3,-3);this.scene.add(fill);this.ray=new T.Raycaster();this.pointer=new T.Vector2();this.targets=[];this.byId=new Map();this.floaters=[];this.animations=[];this.time=0;this.paused=false;this.rect={};this.textures=new T.TextureLoader();this.clock=new T.Clock();this.resize=()=>{const b=host.getBoundingClientRect();this.renderer.setSize(b.width,b.height);this.camera.aspect=b.width/b.height;this.camera.lookAt(0,b.height<740?1.15:.35,0);this.camera.fov=b.width>b.height?45:43;this.camera.updateProjectionMatrix();};window.addEventListener('resize',this.resize);this.resize();let down;this.renderer.domElement.addEventListener('pointerdown',e=>{if(this.paused)return;down={x:e.clientX,y:e.clientY};});this.renderer.domElement.addEventListener('pointerup',e=>{if(!down||this.paused)return;const p=down;down=null;if(Math.hypot(e.clientX-p.x,e.clientY-p.y)>25)return;const b=host.getBoundingClientRect();this.pointer.set((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1);this.ray.setFromCamera(this.pointer,this.camera);for(const h of this.ray.intersectObjects(this.targets,true)){let o=h.object;while(o&&!o.userData.id)o=o.parent;if(o){this.pick(o.userData.id);break;}}});this.render=this.render.bind(this);requestAnimationFrame(this.render);}
 mat(color,roughness=.57){return new T.MeshStandardMaterial({color,roughness,metalness:0});}
 mesh(geo,mat,parent=this.root){const o=new T.Mesh(geo,typeof mat==='string'?this.mat(mat):mat);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;}
 ell(pos,scale,color,parent=this.root){const m=this.mesh(new T.SphereGeometry(1,32,20),color,parent);m.position.set(...pos);m.scale.set(...scale);return m;}
 tube(points,r,color,parent=this.root){return this.mesh(new T.TubeGeometry(new T.CatmullRomCurve3(points.map(p=>new T.Vector3(...p))),24,r,10,false),color,parent);}
 item(id,pos){const g=new T.Group();g.position.set(...pos);g.userData.id=id;this.root.add(g);this.targets.push(g);this.byId.set(id,g);return g;}
 label(text,pinyin='',w=1.5,h=.9,color='#fff6dc'){const c=document.createElement('canvas');c.width=512;c.height=320;const x=c.getContext('2d');x.fillStyle=color;x.fillRect(0,0,c.width,c.height);x.strokeStyle='#c7ac70';x.lineWidth=14;x.strokeRect(12,12,488,296);x.fillStyle='#244e40';x.textAlign='center';x.textBaseline='middle';x.font=`600 ${text.length>4?70:text.length>2?98:152}px "PingFang SC","Microsoft YaHei",sans-serif`;x.fillText(text,256,pinyin?206:169);if(pinyin){x.font='72px Arial';x.fillStyle='#637355';x.fillText(pinyin,256,78);}const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;const mat=new T.MeshBasicMaterial({map:tex});const m=new T.Mesh(new T.BoxGeometry(w,h,.085),[this.mat('#bca077'),this.mat('#bca077'),this.mat('#bca077'),this.mat('#bca077'),mat,this.mat('#cfbb91')]);m.castShadow=true;m.userData.billboard=true;return m;}
 plaque(g,text,pinyin='',w=1.5,h=.9){const l=this.label(text,pinyin,w,h);g.add(l);l.position.y=.5;return l;}
 async loadCast(){if(this.castPromise)return this.castPromise;this.cast=new Map();const loader=new GLTFLoader();return this.castPromise=Promise.all(['girl','friend','brother'].map(async actor=>{const data=await loader.loadAsync(`assets/cinema/actor-${actor}.glb`);this.cast.set(actor,data.scene);})).catch(e=>{this.castPromise=null;this.cast=null;throw e;});}
 portrait(g,file,name){const model=this.cast.get(file).clone(true);const bounds=new T.Box3().setFromObject(model),size=bounds.getSize(new T.Vector3()),center=bounds.getCenter(new T.Vector3());const scale=1.85/size.y;model.scale.setScalar(scale);model.position.set(-center.x*scale,-bounds.min.y*scale,-center.z*scale);model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;o.userData.sharedCast=true;}});g.add(model);g.userData.actor=model;this.floaters.push(model);if(name){const lab=this.label(name,'',1.65,.42);lab.position.set(0,-.04,.30);g.add(lab);}}
 cancelMoves(){for(const a of this.animations)a.resolve(false);this.animations=[];}
 reset(kind){this.cancelMoves();this.kind=kind;this.targets=[];this.byId.clear();this.floaters=[];this.animations=[];this.root.traverse(o=>{if(o.isMesh&&!o.userData.sharedCast){o.geometry.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material]){m.map?.dispose();m.dispose();}}});this.root.clear();this.camera.position.set(0,6.7,10.4);this.camera.lookAt(0,this.host.clientHeight<740?1.15:.35,0);this.scene.background=new T.Color('#819f86');this.scene.fog=new T.Fog('#819f86',14,28);const floor=this.mesh(new T.CylinderGeometry(5.8,5.9,.22,80),'#e1d1a2');floor.position.y=-.28;for(let i=0;i<12;i++){const a=i/12*Math.PI*2;const p=this.ell([Math.cos(a)*5.5,.2,Math.sin(a)*5.5],[.65,.5,.6],i%2?'#679279':'#93af80');}for(let i=0;i<14;i++){const a=i*2.4,r=4.4;this.ell([Math.cos(a)*r,-.08,Math.sin(a)*r],[.09,.08,.09],'#f1d186');}}
 clues(){this.reset('clues');const nut=this.item('nut',[-1.8,.12,.15]);this.ell([0,.36,0],[.33,.42,.29],'#9d5b2d',nut);this.ell([0,.68,0],[.37,.18,.33],'#71492b',nut);this.tube([[0,.81,0],[.05,1.0,.01]],.04,'#715538',nut);this.plaque(nut,'松子壳','',1.3,.38).position.set(0,-.1,.7);const footprints=this.item('prints',[1.55,.1,.25]);for(let i=0;i<5;i++){const f=this.ell([(i%2-.5)*.38,.012,-i*.30],[.10,.018,.19],'#795b39',footprints);f.rotation.y=.16;}this.plaque(footprints,'小脚印','',1.3,.38).position.set(0,-.1,.7);const shadow=this.item('shadow',[0,.01,2]);this.ell([0,0,0],[.8,.015,.34],'#807d69',shadow);this.plaque(shadow,'灯影','',1.2,.38).position.set(0,.1,.1);const moon=this.item('moon',[0,1.5,-1.7]);this.ell([0,0,0],[.6,.6,.15],'#f6d782',moon);this.floaters.push(moon);}
 crew(){this.reset('crew');const boat=this.item('boat',[0,.2,1.1]);this.ell([0,0,0],[2.45,.42,1.1],'#438e87',boat);this.tube([[-2.2,.2,.2],[0,.19,1.0],[2.2,.2,.2]],.06,'#e2be6e',boat);for(let i=0;i<3;i++){const seat=this.item('seat-'+i,[(i-1)*1.45,.67,1.25]);this.ell([0,0,0],[.63,.10,.62],i?'#e5acb4':'#f5d799',seat);if(i===0)this.plaque(seat,'珞伊','',1.05,.48).position.set(0,.35,.22);this.byId.set('seat-'+i,seat);}for(const [i,actor,name]of [[0,'friend','李欣袆'],[1,'girl','杨诗然'],[2,'brother','乔治哥哥']]){const person=this.item('friend-'+['a','b','c'][i],[(i-1)*1.85,.12,-2.6]);this.portrait(person,actor,name);}this.floaters.push(boat);}
 steps(){this.reset('steps');this.scene.background=new T.Color('#739e94');const water=this.mesh(new T.PlaneGeometry(11,11),new T.MeshStandardMaterial({color:'#559eaa',roughness:.2,metalness:.2}));water.rotation.x=-Math.PI/2;water.position.y=-.14;const shapes=['circle','triangle','circle','triangle','circle'];shapes.forEach((shape,i)=>{const x=i%2===0?-.55:.55,z=2-i*1.12;const g=this.item('stone-'+i,[x,0,z]);const stone=this.mesh(new T.CylinderGeometry(.64,.70,.18,shape==='circle'?48:3),i%2?'#dcada0':'#d9d7b0',g);if(i%2)stone.rotation.y=Math.PI/2;for(const a of (i%2?[0]:[-.16,.16]))this.ell([a,.11,0],[.08,.01,.19],'#407d72',g);g.userData.shape=shape;});this.hedgehog=this.item('hedgehog',[-.55,.25,3.1]);this.ell([0,.2,0],[.34,.24,.35],'#8b6240',this.hedgehog);this.ell([0,.19,.25],[.21,.14,.15],'#ecd4a7',this.hedgehog);this.ell([0,.19,.37],[.05,.04,.05],'#2e3d37',this.hedgehog);for(const a of [-.09,.09])this.ell([a,.25,.30],[.026,.029,.02],'#29352d',this.hedgehog);}
 wordWorld(){this.reset('words');const sky=this.item('sky',[-1.65,.4,-1]);for(let i=0;i<4;i++)this.ell([i*.25-.37,.85+(i%2)*.12,0],[.40,.31,.18],'#fff9e5',sky);const earth=this.item('earth',[0,.05,-.7]);this.ell([0,.2,0],[.64,.27,.43],'#629564',earth);this.tube([[0,.25,0],[0,.85,0]],.035,'#538752',earth);const leaf=this.ell([.16,.65,0],[.24,.1,.06],'#86b366',earth);leaf.rotation.z=.4;const person=this.item('person',[1.65,.05,-1]);this.portrait(person,'girl','');const words=[['地','dì','di'],['人','rén','ren'],['天','tiān','tian']];words.forEach((w,i)=>{const g=this.item(w[2],[(i-1)*1.75,.25,1.5]);this.plaque(g,w[0],w[1],1.40,1.16);});}
 pronouns(){this.reset('pronouns');const self=this.item('self',[0,.15,2.0]);this.plaque(self,'珞伊','',1.7,.8);this.ell([-.32,.12,.37],[.15,.08,.21],'#edc3a2',self);this.ell([.32,.12,.37],[.15,.08,.21],'#edc3a2',self);const friend=this.item('friend',[-1.5,.1,-.75]);this.portrait(friend,'friend','李欣袆');const brother=this.item('brother',[1.5,.1,-.75]);this.portrait(brother,'brother','乔治哥哥');}
 move(id,target){const o=this.byId.get(id);if(!o)return Promise.resolve();const from=o.position.clone(),to=new T.Vector3(...target);return new Promise(resolve=>this.animations.push({o,from,to,t:0,d:.8,resolve}));}
 invite(id,seat){return this.move(id,seat<3?[(seat-1)*1.45,.82,1.25]:[-1.85,.12,-2.6]);}
 shore(id){return this.move(id,[(['friend-a','friend-b','friend-c'].indexOf(id)-1)*1.85,.12,-2.6]);}
 glow(id){const o=this.byId.get(id);if(!o)return;o.traverse(m=>{if(m.isMesh)for(const mat of Array.isArray(m.material)?m.material:[m.material]){if('emissive' in mat){mat.emissive=new T.Color('#f5c865');mat.emissiveIntensity=.06;}}});}
 setActive(id){for(const [key,g] of this.byId){if(key.startsWith('stone'))g.scale.setScalar(key===id?1.13:1);}this.glow(id);if(!this.stepMarker?.parent){this.stepMarker=this.mesh(new T.ConeGeometry(.13,.30,24),'#dcab44');this.stepMarker.rotation.z=Math.PI;}const o=this.byId.get(id);if(o)this.stepMarker.position.copy(o.position).add(new T.Vector3(0,.62,0));}
 positions(){const bounds=this.host.getBoundingClientRect();return Object.fromEntries([...this.byId].map(([id,o])=>{const visibleMesh=o.children.find(c=>c.isMesh)||o;const v=new T.Vector3();if(o.userData.actor){let head;o.userData.actor.traverse(m=>{if(m.name.startsWith('GEO-spring_head'))head=m;});new T.Box3().setFromObject(head||o.userData.actor).getCenter(v);}else visibleMesh.getWorldPosition(v);v.project(this.camera);return [id,{x:bounds.left+(v.x*.5+.5)*bounds.width,y:bounds.top+(-v.y*.5+.5)*bounds.height}];}));}
 render(){requestAnimationFrame(this.render);const dt=Math.min(this.clock.getDelta(),.1);if(this.host.style.display==='none')return;const fov=this.camera.aspect<.5?52:43;if(this.camera.fov!==fov){this.camera.fov=fov;this.camera.updateProjectionMatrix();}if(!this.paused){this.time+=dt;for(const o of this.floaters)o.rotation.z=Math.sin(this.time*1.3)*.018;for(let i=this.animations.length-1;i>=0;i--){const a=this.animations[i];a.t+=dt;const u=Math.min(1,a.t/a.d),e=u*u*(3-2*u);a.o.position.lerpVectors(a.from,a.to,e);a.o.position.y+=Math.sin(u*Math.PI)*.35;if(u===1){this.animations.splice(i,1);a.resolve();}}}this.root.traverse(o=>{if(o.userData.billboard)o.quaternion.copy(this.camera.quaternion);});this.renderer.render(this.scene,this.camera);}
}
