import {StoryStage} from './cinema-world.js';
const $=id=>document.getElementById(id),film=$('film'),AS='assets/cinema/',KEY='luoyi-cinema-v1';
const EMPTY=()=>({v:1,math:{index:0,done:false,events:[]},chinese:{index:0,done:false,events:[],oral:'未观察朗读'},note:''});
function validatedSave(d){if(d?.v!==1||!['math','chinese'].every(s=>d[s]&&Number.isInteger(d[s].index)&&d[s].index>=0&&d[s].index<20&&typeof d[s].done==='boolean'&&Array.isArray(d[s].events)&&d[s].events.length<=800&&d[s].events.every(e=>e&&typeof e==='object'&&!Array.isArray(e)&&typeof e.kind==='string'&&e.kind.length<80&&Object.values(e).every(v=>v===null||['string','number','boolean'].includes(typeof v)))))throw Error('Invalid progress');return {v:1,math:{index:d.math.index,done:d.math.done,events:d.math.events},chinese:{index:d.chinese.index,done:d.chinese.done,events:d.chinese.events,oral:String(d.chinese.oral||'未观察朗读').slice(0,40)},note:String(d.note||'').slice(0,400)};}
let save;try{save=validatedSave(JSON.parse(localStorage.getItem(KEY)));}catch{save=EMPTY();}
let timeline,clips=[],subject=null,index=0,stage,task=null,busy=false,paused=false,token=0,lastTime=0,wasPlaying=false,returnFinish=false,hintAudio=new Audio(),toastTimer,loadTimer,lesson='';
const words=[['天','tiān','tian'],['地','dì','di'],['人','rén','ren'],['你','nǐ','ni'],['我','wǒ','wo'],['他','tā','ta']];
const ruby=(h,p)=>`<ruby>${h}<rt>${p}</rt></ruby>`;
const lessonFor=s=>s==='math'?'数学｜数学游戏·操场活动 · 第4—5页（本集选练）':'语文｜识字第1课《天地人》· 第8页';
function persist(){try{localStorage.setItem(KEY,JSON.stringify(save));}catch{toast('此浏览器未能保存进度，可在家长手记导出。');}}
function event(kind,details={}){if(!subject)return;save[subject].events.push({time:new Date().toISOString(),clip:clips[index]?.id,kind,...details});if(save[subject].events.length>800)save[subject].events.splice(0,save[subject].events.length-800);persist();if(kind==='开始互动'){const intro={clues:'clues-start',letters:'letters-start'}[details.task];if(intro)sound(intro);}if(kind==='探索线索'&&task?.found.size===0&&['nut','prints'].includes(details.object))sound('clue-'+details.object);}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3000);}
function loading(on,message){$('loading').hidden=!on;$('retry').hidden=true;if(message)$('loading-text').textContent=message;clearTimeout(loadTimer);if(on)loadTimer=setTimeout(()=>{$('loading-text').textContent='这段画面还在赶来，网络恢复后可以重试。';$('retry').hidden=false;},15000);}
function button(label,action,secondary=false){const b=document.createElement('button');b.innerHTML=label;b.classList.toggle('secondary',secondary);b.onclick=()=>{if(!paused&&!busy)action();};$('task-controls').append(b);return b;}
async function sound(id){hintAudio.pause();hintAudio.src=AS+id+'.mp3';try{await hintAudio.play();}catch{toast('请再点一次播放声音。');}}
function clearTask(){$('app').classList.remove('radio-on');film.classList.remove('boat-closeup');$('poster').classList.remove('boat-closeup');task=null;busy=false;stage?.cancelMoves();$('game').style.display='none';$('knowledge').hidden=true;$('knowledge').classList.remove('live');$('knowledge').replaceChildren();$('task-banner').hidden=true;$('task-controls').replaceChildren();$('caption').hidden=false;}
function getStage(){if(!stage){try{stage=new StoryStage($('game'),pick);}catch{toast('此设备未能开启三维画面，请换 Safari 或更新浏览器。');throw Error('WebGL not available');}}return stage;}
async function start(s){if(!timeline){toast('画面正在准备，请稍候。');return;}subject=s;clips=timeline.clips.filter(c=>c.subject===s);index=save[s].done?0:Math.min(save[s].index,clips.length-1);$('home').hidden=true;$('playing').hidden=false;$('lesson-text').textContent=lessonFor(s);lesson=lessonFor(s);event('进入故事');await showClip();}
async function showClip(){
 const mine=++token;clearTask();hintAudio.pause();paused=false;if(stage)stage.paused=false;
 const c=clips[index];save[subject].index=index;persist();$('next').hidden=true;const boatClose=c.actor==='boat'&&c.camera==='boat';film.classList.toggle('boat-closeup',boatClose);$('poster').classList.toggle('boat-closeup',boatClose);$('app').classList.toggle('radio-on',c.speaker.includes('联络扣'));
 $('chapter').textContent=subject==='math'?'月光森林 · 月亮怎么长脚了':'月光森林 · 谁把名字送错了';
 $('speaker').textContent=c.speaker;$('line').textContent=c.text;$('progress').textContent=`${index+1} / ${clips.length}`;
 film.classList.remove('ready');$('poster').src=AS+c.id+'.jpg';loading(true);
 film.onloadeddata=()=>{if(mine!==token)return;loading(false);film.classList.add('ready');if(paused)film.pause();};
 film.onerror=()=>{if(mine!==token)return;loading(true,'这段画面暂时没有加载成功。');$('retry').hidden=false;clearTimeout(loadTimer);};
 film.src=AS+c.id+'.mp4';film.load();
 // Invoke play during the original touch event; waiting for loadeddata loses that privilege on Safari.
 try{await film.play();}catch{if(mine!==token||paused)return;$('next').hidden=false;$('next').textContent='点这里开始播放';}
}
function captionParts(){const c=clips[index];if(!c||task)return;const parts=c.text.match(/[^。！？；]+[。！？；]?/g)||[c.text],clean=s=>s.replace(/[^\p{L}\p{N}]/gu,'');if(c.words?.length){let cursor=0;const words=c.words.map(w=>{const item={t:w.t,n:cursor};cursor+=clean(w.text).length;return item;});cursor=0;let at=0;for(let i=0;i<parts.length;i++){const when=words.find(w=>w.n>=cursor)?.t??c.duration;if(film.currentTime-.2>=when)at=i;cursor+=clean(parts[i]).length;}$('line').textContent=parts[at];return;}const ratio=Math.max(0,Math.min(1,(film.currentTime-.2)/c.duration));const lengths=parts.map(t=>t.length),total=lengths.reduce((a,b)=>a+b,0);let n=ratio*total,at=0;while(at<parts.length-1&&n>lengths[at])n-=lengths[at++];$('line').textContent=parts[at];}
film.addEventListener('timeupdate',()=>{
 captionParts();const c=clips[index];if(!c||task)return;
 if(c.id==='m08'){
  const t=film.currentTime-.2,round=(c.words||[]).find(w=>w.text==='圆圈')?.t??2.05,triangle=(c.words||[]).find(w=>w.text==='三角')?.t??3.43;
  if(t>=round){const second=t>=triangle;$('knowledge').hidden=false;$('knowledge').classList.add('live');$('knowledge').innerHTML=`<span>${second?ruby('三角形','sān jiǎo xíng'):ruby('圆圈','yuán quān')} → ${second?ruby('单脚','dān jiǎo'):ruby('双脚','shuāng jiǎo')}</span>`;}else $('knowledge').hidden=true;
  return;
 }
 if(!['c02','c05','c06'].includes(c.id))return;
 // Keep the teaching focus through its explanation; incidental pronouns must not replace it.
 const focus=c.id==='c02'?['天','地','人']:['我','你','他'];
 const cues=focus.map(char=>{const occurrences=(c.words||[]).filter(w=>w.text===char);return c.id==='c06'?occurrences.at(-1):occurrences[0];}).filter(Boolean).sort((a,b)=>a.t-b.t);
 const cue=cues.filter(w=>w.t<=film.currentTime-.2).at(-1),current=words.find(w=>w[0]===cue?.text);
 if(current){$('knowledge').hidden=false;$('knowledge').classList.add('live');$('knowledge').innerHTML=`<span>${ruby(current[0],current[1])}</span>`;}else $('knowledge').hidden=true;
});
film.addEventListener('ended',()=>{if(paused)return;event('观看片段');const c=clips[index];if(c.task)beginTask(c.task);else{$('next').hidden=false;$('next').textContent='继续故事 ›';}});
$('next').onclick=()=>{if(paused)return;if(film.paused&&!film.ended&&film.currentTime<film.duration-.1){film.play().then(()=>{$('next').hidden=true;}).catch(()=>toast('声音暂未打开，请重试。'));return;}advance();};
function advance(){hintAudio.pause();if(index<clips.length-1){index++;showClip();}else finish();}
function instruction(title,hint){$('task-heading').textContent=title;$('task-hint').textContent=hint;$('task-banner').hidden=false;$('caption').hidden=true;$('next').hidden=true;}
async function beginTask(type){clearTask();film.pause();task={type,attempts:0,hints:0,selected:null,found:new Set(),round:0};if(type.endsWith('-finish')){finish();return;}if(type==='world'||type==='pronouns-demo'){demo(type);return;}$('game').style.display='block';const world=getStage(),active=task;loading(true,'伙伴正在来到森林…');try{if(['crew','letters','pronouns'].includes(type))await world.loadCast();else world.loadCast().catch(()=>{});}catch{if(task!==active)return;loading(true,'伙伴暂时没有加载好，请重试。');$('retry').hidden=false;clearTimeout(loadTimer);return;}if(task!==active)return;loading(false);world.resize();if(type==='clues'){world.clues();instruction('珞伊，先找线索','点一点画面里的东西，找两条能连起来的线索。');button('听听线索',()=>hint('clue-hint'),true);}if(type==='crew'){world.crew();instruction('珞伊来邀请伙伴','你已经在船上。邀请伙伴后，检查三个座位。');button('开船！',checkCrew);button('再听规则',()=>hint('crew-hint'),true);}if(type==='steps'){world.steps();world.setActive('stone-0');instruction('珞伊，送小刺猬过桥','看当前亮起的踏板，选择怎样迈出这一步。');button(`${ruby('双脚','shuāng jiǎo')} ◯`,()=>step('circle'));button(`${ruby('单脚','dān jiǎo')} △`,()=>step('triangle'));button('看规则',()=>hint('step-hint'),true);}if(type==='letters'){world.wordWorld();instruction('珞伊，把信送回家','先点字牌，再点天空、土地或画面中的人。');button('听这个字',()=>{if(task.selected)sound('read-'+task.selected);else toast('先点一张字牌。');},true);}if(type==='pronouns'){world.pronouns();pronounRound();button('听听方法',()=>hint('pronoun-hint'),true);}event('开始互动',{task:type});}
function demo(type){$('knowledge').hidden=false;if(type==='world'){instruction('三个名字，三个地方','听完后，可以点字再听一次。');for(const [h,p,id]of words.slice(0,3)){const b=document.createElement('button');b.innerHTML=ruby(h,p);b.onclick=()=>sound('read-'+id);$('knowledge').append(b);}button('来送名字信',advance);}else{instruction('听谁在说话，再认“我、你、他”','普通对白中的女性仍用“她”；本课学习的是“他”。');for(const [h,p,id]of [words[4],words[3],words[5]]){const b=document.createElement('button');b.innerHTML=ruby(h,p);b.onclick=()=>sound('read-'+id);$('knowledge').append(b);}button('换珞伊来试',advance);}event('学习示范',{task:type});}
function hint(id){if(task){task.hints++;event('使用提示',{task:task.type});}sound(id);}
async function pick(id){if(!task||busy||paused)return;const active=task,type=task.type;if(type==='clues'){task.attempts++;event('探索线索',{object:id});if(id==='nut'||id==='prints'){task.found.add(id);stage.glow(id);toast(id==='nut'?'松子壳刚落下，旁边还有小脚印。':'小脚印一路朝竹林去了。');if(task.found.size===2)completeTask('把两条线索连起来了。');}else{hint('clue-hint');}}else if(type==='crew'&&id.startsWith('friend-')){busy=true;if(task.found.has(id))task.found.delete(id);else task.found.add(id);const invited=[...task.found];await Promise.all(['friend-a','friend-b','friend-c'].map(who=>invited.includes(who)?stage.invite(who,invited.indexOf(who)+1):stage.shore(who)));if(task!==active)return;busy=false;event('调整邀请',{invited:task.found.size});}else if(type==='letters'){if(['tian','di','ren'].includes(id)){if(task.found.has(id))return;task.selected=id;stage.glow(id);$('task-hint').textContent='这封信要送到哪里？点画面中的地方。';}else if(['sky','earth','person'].includes(id)&&task.selected){const letter=task.selected,expected={tian:'sky',di:'earth',ren:'person'}[letter];task.attempts++;event('字义匹配',{letter,target:id,correct:id===expected});if(id!==expected){hint('letter-hint');return;}busy=true;task.found.add(letter);const dest=stage.byId.get(id).position.clone();await stage.move(letter,[dest.x,dest.y+.7,dest.z+.3]);if(task!==active)return;busy=false;task.selected=null;if(task.found.size===3)completeTask('三封信都找到家了。');else toast('送到了！再送下一封。');}}else if(type==='pronouns'){const q=pronounQuestions[task.round];if(!['self','friend','brother'].includes(id))return;task.attempts++;event('称呼判断',{speaker:q.speaker,word:q.word,target:id,correct:id===q.target});if(id!==q.target){hint('pronoun-hint');return;}stage.glow(id);task.round++;if(task.round===pronounQuestions.length)completeTask('换了说话人，你也找到了正确的人。');else pronounRound();}}
function checkCrew(){task.attempts++;const correct=task.found.size===2;event('检查三人组',{invited:task.found.size,selfSeatShown:true,correct});if(correct)completeTask('珞伊和两位伙伴，共三位。');else{hint('crew-hint');if(task.found.size>2)toast('船上还有珞伊。再点一位伙伴，请这位伙伴坐下一班。');}}
async function step(shape){const active=task,current=task.round,expected=current%2?'triangle':'circle';task.attempts++;event('踏板规则',{step:current+1,shape,correct:shape===expected});if(shape!==expected){hint('step-hint');return;}busy=true;const pos=stage.byId.get('stone-'+current).position;await stage.move('hedgehog',[pos.x,.25,pos.z]);if(task!==active)return;busy=false;task.round++;if(task.round===5)completeTask('五块踏板都走过了，小刺猬到家啦。');else stage.setActive('stone-'+task.round);}
const pronounQuestions=[{speaker:'李欣袆',word:'我',py:'wǒ',target:'friend',hint:'李欣袆正在对珞伊说话。'},{speaker:'李欣袆',word:'你',py:'nǐ',target:'self',hint:'还是李欣袆在对珞伊说话。'},{speaker:'珞伊',word:'我',py:'wǒ',target:'self',hint:'现在轮到珞伊对李欣袆说话。'},{speaker:'珞伊',word:'你',py:'nǐ',target:'friend',hint:'珞伊正在对李欣袆说话。'},{speaker:'珞伊',word:'他',py:'tā',target:'brother',hint:'珞伊和李欣袆说起旁边的乔治哥哥。'}];
function pronounRound(){const q=pronounQuestions[task.round];instruction('谁是这句里的“'+q.word+'”？',q.hint);$('knowledge').hidden=false;$('knowledge').innerHTML=`<button id="pronoun-sound">${ruby(q.word,q.py)} ♫</button>`;$('pronoun-sound').onclick=()=>sound('read-'+({我:'wo',你:'ni',他:'ta'}[q.word]));sound('pronoun-'+task.round);}
function completeTask(message){event('完成互动',{task:task.type,attempts:task.attempts,hints:task.hints});busy=true;instruction('珞伊找到办法啦',message);$('task-controls').replaceChildren();const b=button('继续故事 ›',()=>{busy=false;advance();});b.onclick=()=>{busy=false;advance();};sound('good');}
function finish(){save[subject].done=true;persist();clearTask();film.pause();$('playing').hidden=true;$('finish-title').textContent=subject==='math'?'珞伊，把月亮送回来了。':'珞伊，把森林的名字找回来了。';$('finish-copy').textContent=subject==='math'?'你连起线索、把自己也算进三人船，还帮助小刺猬走过踏板。':'天、地、人有了自己的位置；换了说话人，“我”和“你”也会跟着换。';$('reading').hidden=subject!=='chinese';$('oral-observation').value=save.chinese.oral||'未观察朗读';const box=document.querySelector('.reading-words');box.replaceChildren();for(const [h,p,id]of words){const b=document.createElement('button');b.innerHTML=ruby(h,p);b.onclick=()=>sound('read-'+id);box.append(b);}$('finish').showModal();event('完成本集');}
function goHome(){token++;film.pause();hintAudio.pause();clearTask();for(const d of document.querySelectorAll('dialog[open]'))d.close();paused=false;loading(false);subject=null;$('home').hidden=false;$('playing').hidden=true;film.classList.remove('ready');$('poster').src=AS+'cover.jpg';$('lesson-text').textContent='珞伊的小小冒险，从这里开始';}
function pause(){if($('rest').open||!$('home').hidden)return;paused=true;wasPlaying=!film.paused||(!task&&film.readyState<2);film.pause();hintAudio.pause();if(stage)stage.paused=true;$('rest').showModal();}
$('pause').onclick=pause;$('resume').onclick=()=>{$('rest').close();paused=false;if(stage)stage.paused=false;if(wasPlaying&&!task)film.play().catch(()=>{$('next').hidden=false;});};$('go-home').onclick=goHome;$('finish-home').onclick=goHome;
$('oral-observation').onchange=()=>{save.chinese.oral=$('oral-observation').value;persist();};
$('choose-math').onclick=()=>start('math');$('choose-chinese').onclick=()=>start('chinese');$('retry').onclick=()=>subject?showClip():location.reload();
$('cancel-loading').onclick=goHome;
$('replay').onclick=()=>{if(task){const hints={clues:'clue-hint',crew:'crew-hint',steps:'step-hint',letters:'letter-hint',pronouns:'pronoun-hint'};if(hints[task.type]){hint(hints[task.type]);return;}}hintAudio.pause();film.currentTime=0;film.play().catch(()=>toast('点一下“继续故事”播放。'));$('next').hidden=true;event('重看片段');};
function reportText(){let lines=['珞伊的蜻蜓剧场｜家庭观察手记',new Date().toLocaleString('zh-CN'),''];for(const s of ['math','chinese']){const r=save[s],done=r.events.filter(e=>e.kind==='完成互动'),hints=r.events.filter(e=>e.kind==='使用提示').length;lines.push(lessonFor(s),r.done?'本集已走到结尾':'本集尚未完成',`已记录互动 ${done.length} 次；提示出现 ${hints} 次。`);for(const e of done){const names={clues:'两条线索关联',crew:'包括自己的三人组',steps:'圆圈双脚／三角形单脚',letters:'有拼音和情境支持的字义匹配',pronouns:'交换说话人的称呼判断'};lines.push(`· ${names[e.task]||e.task}：本次操作 ${e.attempts} 次，使用提示 ${e.hints} 次。`);}if(s==='chinese')lines.push('朗读由家长观察：'+(r.oral||'未观察朗读'));lines.push('');}lines.push('家长补充：'+(save.note||'暂未填写'),'','说明：只记录本游戏中的行为，不计算掌握率，不推断智力或注意力水平。','数学是第4—5页选练；语文是第8页六字的学习活动，独立认读仍需家长另行观察。','记录未自动发送给教师或 Codex。');return lines.join('\n');}
function openParent(){wasPlaying=!film.paused;film.pause();hintAudio.pause();paused=true;if(stage)stage.paused=true;$('report').textContent=reportText();$('parent-note').value=save.note||'';$('parents').showModal();}
function closeParent(){save.note=$('parent-note').value.trim();persist();$('parents').close();paused=false;if(stage)stage.paused=false;if(returnFinish){returnFinish=false;$('finish').showModal();}else if(wasPlaying&&subject&&!task)film.play().catch(()=>{});}
$('parent').onclick=openParent;$('finish-report').onclick=()=>{returnFinish=true;$('finish').close();openParent();};document.querySelector('[data-close]').onclick=closeParent;$('parents').addEventListener('cancel',e=>{e.preventDefault();closeParent();});$('rest').addEventListener('cancel',e=>e.preventDefault());$('finish').addEventListener('cancel',e=>{e.preventDefault();goHome();});
function download(text,name,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
$('parent-note').oninput=()=>{save.note=$('parent-note').value;persist();$('report').textContent=reportText();};$('save-report').onclick=()=>download(reportText(),'珞伊的故事手记.txt','text/plain;charset=utf-8');$('copy-report').onclick=async()=>{try{await navigator.clipboard.writeText(reportText());$('report-status').textContent='已复制，可由家长粘贴分享。';}catch{$('report-status').textContent='复制未成功，请用“保存报告”。';}};
$('export-progress').onclick=()=>download(JSON.stringify(save),'珞伊剧场进度.json','application/json');$('import-progress').onchange=async e=>{try{const f=e.target.files[0];if(!f||f.size>500000)throw Error();const d=validatedSave(JSON.parse(await f.text()));save=d;persist();returnFinish=false;goHome();openParent();$('report').textContent=reportText();$('report-status').textContent='进度已导入。';}catch{$('report-status').textContent='文件格式不对，没有更改进度。';}e.target.value='';};
document.addEventListener('visibilitychange',()=>{if(document.hidden&&subject&&!$('parents').open&&!$('finish').open)pause();});
async function prepareExistingWorker(){
 if(!navigator.serviceWorker?.controller)return;
 const registration=await navigator.serviceWorker.getRegistration();if(!registration)return;
 loading(true,'正在准备动画播放…');await registration.update();
 const worker=registration.installing||registration.waiting;
 if(worker&&worker.state!=='activated')await new Promise((resolve,reject)=>{
  const timer=setTimeout(()=>{worker.removeEventListener('statechange',check);reject(Error('worker timeout'));},20000);
  function check(){if(worker.state==='activated'){clearTimeout(timer);worker.removeEventListener('statechange',check);resolve();}else if(worker.state==='redundant'){clearTimeout(timer);worker.removeEventListener('statechange',check);reject(Error('worker update'));}}
  worker.addEventListener('statechange',check);check();
 });
}
Promise.all([fetch(AS+'timeline.json').then(r=>{if(!r.ok)throw Error('timeline');return r.json();}),prepareExistingWorker()]).then(([d])=>{timeline=d;window.cinemaReady=true;loading(false);}).catch(()=>{loading(true,'动画目录暂时没准备好，请联网后重试。');$('retry').hidden=false;clearTimeout(loadTimer);});
// Read-only runtime diagnostics used for QA, not an answer or completion bypass.
window.cinemaInspect=()=>({subject,index,clip:clips[index]?.id,task:task?.type,round:task?.round,busy,selected:task?[...task.found]:[],paused,positions:stage?.positions(),media:{time:film.currentTime,duration:film.duration,paused:film.paused},events:subject?save[subject].events:[]});
