import {EPISODES,CAST,ruby} from './journey-data.js?v=math4';
import {JourneyWorld} from './journey-world.js?v=math4';
const KEY='luoyi-journey-v1',AS='assets/cinema/';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const blank=()=>({v:1,episodes:{},events:[],note:''});
function valid(d){if(d?.v!==1||!d.episodes||Array.isArray(d.episodes)||typeof d.episodes!=='object'||!Array.isArray(d.events)||d.events.length>1500)throw Error('无效记录');const result=blank();for(const [id,p]of Object.entries(d.episodes)){const ep=EPISODES.find(e=>e.id===id);if(!ep||!Number.isInteger(p.beat)||p.beat<0||p.beat>=ep.beats.length||typeof p.done!=='boolean')throw Error('分集记录不符');result.episodes[id]={beat:p.beat,done:p.done};}for(const e of d.events){if(!e||typeof e!=='object'||!EPISODES.some(p=>p.id===e.episode)||!['操作','尝试','完成','提示','重听','补充信息','自由选择'].includes(e.kind)||typeof e.task!=='string'||e.task.length>40||typeof e.detail!=='string'||e.detail.length>500||typeof e.time!=='string'||e.time.length>40)throw Error('事件记录不符');result.events.push({episode:e.episode,task:e.task,kind:e.kind,detail:e.detail,time:e.time});}result.note=String(d.note||'').slice(0,600);return result;}
let save;try{save=valid(JSON.parse(localStorage.getItem(KEY)));}catch{save=blank();}
let root,world,voices,ep,beat=0,phase='menu',task,paused=false,audio=new Audio(),cue,audioDone=true,rewardAt=0,generation=0,onClose,prologue,modalResume=false;
audio.preload='auto';audio.setAttribute('playsinline','');
audio.addEventListener('ended',()=>{audioDone=true;if(world)world.talkLevel=0;if(phase==='talk'&&!paused)advance();});
const $=id=>root.querySelector('#j-'+id);
function persist(){try{localStorage.setItem(KEY,JSON.stringify(save));}catch{$('message').textContent='浏览器没有保存成功，可以在家长手记导出进度。';}}
function record(kind,detail=''){save.events.push({episode:ep.id,task:task?.data.id||'story',kind,detail:String(detail).slice(0,500),time:new Date().toISOString()});if(save.events.length>1500)save.events.splice(0,save.events.length-1500);persist();}
function control(text,fn,primary=false,id=''){const b=document.createElement('button');b.innerHTML=text;b.className=primary?'j-primary':'';if(id)b.id='j-'+id;b.onclick=()=>{if(!paused)fn();};$('controls').append(b);return b;}
function setMessage(s){$('message').textContent=s;}
function stopAudio(){audio.pause();cue=null;audioDone=true;if(world)world.talkLevel=0;$('audio').hidden=true;}
function pause(){if(paused||phase==='menu')return;paused=true;audio.pause();if(world)world.paused=true;$('pause').textContent='继续';$('pause').setAttribute('aria-label','继续故事');}
function resume(){if(!paused)return;paused=false;if(world)world.paused=false;$('pause').textContent='暂停';$('pause').setAttribute('aria-label','暂停故事');if(cue&&!audioDone)playAudio();}
async function playAudio(){try{await audio.play();$('audio').hidden=true;}catch{$('audio').hidden=false;}}
async function speak(){const mine=generation;stopAudio();const data=voices.episodes[ep.id],cueBeat=task?.data.type==='meaning'?100+task.round:beat;cue=data.cues.find(c=>c.beat===cueBeat);audioDone=false;const url=new URL(AS+data.file,location.href).href;try{if(audio.src!==url){audio.src=url;await new Promise((resolve,reject)=>{const ok=()=>{clean();resolve();},bad=()=>{clean();reject(Error('声音加载失败'));},timer=setTimeout(bad,20000),clean=()=>{clearTimeout(timer);audio.removeEventListener('loadedmetadata',ok);audio.removeEventListener('error',bad);};audio.addEventListener('loadedmetadata',ok);audio.addEventListener('error',bad);audio.load();});}if(mine!==generation)return;audio.currentTime=cue.start;await playAudio();if(paused)audio.pause();}catch{if(mine===generation){$('audio').hidden=false;setMessage('声音还没有载入，点“播放声音”重试。');}}}
function frame(){if(paused)return;if(cue&&!audioDone&&!audio.paused){const elapsed=audio.currentTime-cue.start;world.talkLevel=cue.env[Math.max(0,Math.floor(elapsed/.04))]||0;if(elapsed>=cue.duration-.035){audio.pause();audioDone=true;world.talkLevel=0;if(phase==='talk')advance();}}if(phase==='reward'&&performance.now()>=rewardAt)advance();}
function showMenu(){generation++;stopAudio();paused=false;if(world){world.active=false;world.paused=true;}phase='menu';ep=null;task=null;$('play').hidden=true;$('menu').hidden=false;$('pause').hidden=true;$('lesson').textContent='数学故事 · 森林巡演';$('cards').innerHTML=EPISODES.map((p,i)=>`<button class="j-episode ${save.episodes[p.id]?.done?'j-done':''}" data-ep="${p.id}" style="--episode-color:${p.color}"><span class="j-number">${p.extra?'番外':String(i+1).padStart(2,'0')}</span><span><b>${p.title}</b><small>${p.extra?'自愿探索，不作课内要求':`${p.lesson} · 第${p.pages}页`}</small></span><span class="j-arrow">${save.episodes[p.id]?.done?'重看':'进入'} →</span></button>`).join('');$('cards').querySelectorAll('[data-ep]').forEach(b=>b.onclick=()=>startEpisode(b.dataset.ep));$('menu').scrollTop=0;}
async function startEpisode(id,restart=false){
 const mine=++generation;ep=EPISODES.find(p=>p.id===id);if(!ep)return;const p=save.episodes[id];beat=restart||p?.done?0:p?.beat||0;paused=false;phase='loading';task=null;stopAudio();$('menu').hidden=true;$('play').hidden=false;$('pause').hidden=false;$('pause').textContent='暂停';$('lesson').textContent=ep.extra?`数学拓展｜${ep.lesson}（自愿探索）`:`数学｜${ep.lesson} · 教材第${ep.pages}页（本集选练）`;$('place').textContent=ep.place;$('heading').textContent='珞伊的巡演队正在准备';$('line').textContent=ep.intro;$('who').textContent='';$('controls').replaceChildren();$('tip').textContent='首次进入需载入人物和声音，请稍候。';setMessage('');
 try{if(!world){world=new JourneyWorld($('canvas'),pick);world.onFrame=frame;}world.active=true;world.paused=false;world.resize();const teachers=['wang','li'].filter(w=>ep.beats.some(b=>b.who===w));await Promise.all([world.loadCast(teachers),voices?Promise.resolve():fetch(AS+'journey-voices.json?v=math4').then(r=>{if(!r.ok)throw Error('voice manifest');return r.json();}).then(d=>voices=d)]);if(mine!==generation)return;world.build(ep);showBeat();}
 catch(e){if(mine!==generation)return;phase='error';$('heading').textContent='这次没有载入完整';$('tip').textContent='可以重试，已玩的记录还在。';control('重新载入',()=>startEpisode(id),true);control('回分集',showMenu);console.error('Journey load',e);}
}
function showBeat(){if(beat>=ep.beats.length)return finish();const b=ep.beats[beat];if(b.type==='splitnew'){const prior=[...save.events].reverse().find(e=>e.episode===ep.id&&e.task==='split'&&e.kind==='操作'&&/^\d\+\d$/.test(e.detail));world.counts=prior?prior.detail.split('+').map(Number):[2,3];}save.episodes[ep.id]={beat,done:!!save.episodes[ep.id]?.done};persist();stopAudio();task=null;$('controls').replaceChildren();setMessage('');$('step').textContent=`${ep.title} · ${beat+1}/${ep.beats.length}`;$('replay').hidden=false;$('help').hidden=true;
 if(b.who){phase='talk';world.shot(b.who,b.action);world.demonstrate(b.action);$('who').textContent=CAST[b.who];$('heading').textContent='';$('line').textContent=b.text;$('tip').textContent='朋友会自动接着讲，珞伊需要帮忙时再动手。';if(b.action==='curtain')world.celebrate(save.events.findLast?.(e=>e.episode===ep.id&&e.kind==='自由选择')?.detail||'dragonfly');speak();}
 else{phase='task';task={data:b,counts:b.setup?[...b.setup]:[...world.counts],initial:b.setup?[...b.setup]:[...world.counts],hints:0,wrong:0,moves:0,selected:null,points:0,round:0,matched:[],relation:'↔',choice:null};$('who').textContent='轮到珞伊';$('heading').innerHTML=ruby(b.title,b.py);$('line').textContent='';$('tip').textContent=b.hint;$('help').hidden=false;setupTask();speak();}
}
function setupTask(){const b=task.data,t=b.type,c=task.counts;const labels=t==='combine'?['原有','新来','全部']:t==='groups'?['备用',...(b.id==='pack'?['第一袋','第二袋','第三袋']:['第一份','第二份','第三份'])]:t==='subtract'||b.id==='remaining'?['车上留下','借给小兔']:t==='split'||t==='splitnew'?['左边','右边']:t==='open'?['备用','演出用']:['左边','右边'];
 if(['clarify','order'].includes(t))world.mail();else if(t==='ending'){world.groups([0]);world.sign('导演');}else world.groups(c,{labels,kind:ep.id==='e03'&&b.id==='three'?'drum':ep.prop,hidden:['hidden','reveal'].includes(t)?1:-1});
 if(t==='pair')world.ducks();if(t==='relation')world.sign('↔');
 if(t==='clarify'){control('问清从哪一边开始',()=>{record('补充信息','主动问清计数起点');success('从蜻蜓小旗这一边开始，再找第二个。');},true,'ask');}
 else if(t==='stamp'){for(let i=0;i<=6;i++)control(String(i),()=>{task.choice=i;world.sign(String(i));$('controls').querySelectorAll('button').forEach(b=>b.classList.remove('j-selected'));$('stamp-'+i).classList.add('j-selected');},false,'stamp-'+i);control('盖章，检查',check,true,'check');}
 else if(t==='hidden'){control('添一粒光点',()=>{if(task.points<6)task.points++;world.sign('●'.repeat(task.points)||'0');setMessage(`珞伊摆了 ${task.points} 粒光点`);},false,'plus');control('收回一粒',()=>{task.points=Math.max(0,task.points-1);world.sign('●'.repeat(task.points)||'0');},false,'minus');control('揭开验证',check,true,'check');}
 else if(t==='relation'){control('转动路牌',rotate,false,'rotate');control('拉铃检查',check,true,'check');}
 else if(t==='meaning'){meaningPrompt();control('这一拨和那一拨全部',()=>meaning('all'),false,'all');}
 else if(t==='ending'){control('蜻蜓飞行秀',()=>{task.choice='dragonfly';record('自由选择','dragonfly');world.celebrate('dragonfly');success('珞伊选的蜻蜓飞起来了。',false);},true,'dragonfly');control('小兔影子戏',()=>{task.choice='rabbit';record('自由选择','rabbit');world.celebrate('rabbit');success('珞伊选的小兔登场了。',false);},false,'rabbit');}
 else if(!['reveal','pair','order','match','identify'].includes(t)){control('拉铃检查',check,true,'check');control('重新摆',()=>{record('操作','主动重新摆放');task.moves++;task.counts=b.setup?[...b.setup]:[0,5];setupTaskReset();},false,'reset');}
 $('access').hidden=false;renderAccessible();
}
function setupTaskReset(){task.selected=null;$('controls').replaceChildren();setupTask();}
function renderAccessible(){const box=$('access-buttons');box.replaceChildren();if(!task)return;const t=task.data.type;const add=(id,label)=>{const b=document.createElement('button');b.textContent=label;b.onclick=()=>pick(id);box.append(b);};if(['order','clarify'].includes(t)){for(let i=0;i<5;i++)add('box-'+i,'从旗子起第'+(i+1)+'个信箱');}else{for(const p of world.props||[]){if(!p.visible||p.userData.paired)continue;add(p.userData.id,`${p.userData.group+1}号盘的一个道具`);}if(t==='pair'){for(let i=0;i<4;i++)add('duck-'+i,'第'+(i+1)+'只小鸭');}else for(let i=0;i<(world.trays?.length||0);i++)add('tray-'+i,'放到'+(i+1)+'号盘');if(t==='reveal')add('cover','打开盖布');}}
function rotate(){task.relation=['<','=','>'][(['<','=','>'].indexOf(task.relation)+1)%3];world.sign(task.relation);}
function incorrect(message){task.wrong++;record('尝试',message);setMessage(message+' 再动手试试，故事等你。');}
function pick(id){if(paused||phase!=='task'||!task)return;const b=task.data,t=b.type;if(t==='clarify'){setMessage('起点还没说清楚，先问一问邮局。');return;}if(t==='order'){if(!id.startsWith('box-'))return;record('操作',id);if(Number(id.slice(4))===b.goal){world.glow(id);success('信箱打开，舞台绳找到了。');}else incorrect('从小旗这一边，一个一个数到第二个');return;}
 if(t==='reveal'){if(id!=='cover')return;world.reveal();record('补充信息','揭盖清点全部物体');success('藏着的一枚也看见了。这回可以完整清点。');return;}
 if(t==='meaning'){const g=id.startsWith('tray-')?+id.slice(5):world.byId.get(id)?.userData.group;if(g===0||g===1)meaning(g===0?'left':'right');return;}
 if(t==='identify'){const g=id.startsWith('tray-')?+id.slice(5):world.byId.get(id)?.userData.group;if(g!==0&&g!==1)return;if((g===0?'left':'right')===b.goal)success('三表示车上留下的三盏，不是借出去的两盏。');else incorrect('看看“留下”指的是哪边');return;}
 if(t==='relation'&&id==='sign'){rotate();return;}
 if(t==='pair'){if(id.startsWith('prop-')){const p=world.byId.get(id);if(p.userData.group!==0)return;task.selected=id;world.select(id);}else if(id.startsWith('duck-')){const d=+id.slice(5);if(task.matched.includes(d)){setMessage('这位已经有帽子了，看看还空着的座位。');return;}if(task.matched.length===3&&!task.extra){task.extra=true;world.extraHat();record('补充信息','发现第4只鸭无帽，取备用帽');setMessage('这位没有帽子！备用箱找来一顶，再给它戴上。');renderAccessible();return;}if(!task.selected){setMessage('先点一顶帽子，再点小鸭。');return;}world.hatOn(task.selected,d);task.matched.push(d);task.selected=null;task.moves++;record('操作',`给第${d+1}只小鸭配帽`);if(task.matched.length===4)success('三顶确实不够。添一顶，四位都有帽子啦。');else if(task.matched.length===3)setMessage('帽子用完了。还有谁没有？点点它。');}return;}
 if(t==='match'){if(!id.startsWith('prop-'))return;const p=world.byId.get(id);if(p.userData.paired){setMessage('这一盏已经配好，找还没连线的。');return;}if(p.userData.group===0){task.selected=id;world.select(id);}else if(task.selected){world.pair(task.selected,id);task.matched.push([task.selected,id]);task.selected=null;world.select(null);record('操作','完成一对一配对');if(task.matched.length===b.goal)success('每盏都恰好配成一对，两边同样多。');}else setMessage('先点左边一盏，再点右边一盏。');renderAccessible();return;}
 if(!['move','split','splitnew','combine','subtract','open','groups'].includes(t))return;
 if(id.startsWith('prop-')){task.selected=id;world.select(id);setMessage('选好啦，再点要送去的托盘。');}
 else if(id.startsWith('tray-')&&task.selected){const to=Number(id.slice(5));if(world.counts[to]>=6){setMessage('这个盘子已经很满了，换一边放。');return;}if(world.transfer(task.selected,to)){task.counts=[...world.counts];task.moves++;record('操作',task.counts.join('+'));task.selected=null;setMessage('位置变了，看看数量怎样变化。');renderAccessible();}}
}
function meaningPrompt(){$('tip').textContent=['3 + 2 = 5。这里的“3”指哪一部分？','3 + 2 = 5。这里的“2”指哪一部分？','3 + 2 = 5。这里的“5”指哪一部分？'][task.round];}
function meaning(which){if(which===task.data.goal[task.round]){record('操作',['指认原有3','指认新来2','指认全部5'][task.round]);task.round++;if(task.round===3)success('3是原有，2是新来，5是两部分合起来的全部。');else{meaningPrompt();speak();}}else incorrect('把数字和刚才的两拨朋友对应起来');}
function check(){if(!task||phase!=='task')return;const b=task.data,c=world.counts,t=b.type;let ok=false;if(t==='stamp')ok=task.choice===b.goal;else if(t==='hidden')ok=task.points===b.goal;else if(t==='relation')ok=task.relation===b.goal;else if(t==='split'||t==='splitnew'){ok=c.reduce((a,v)=>a+v,0)===5&&c.every(n=>n>0);if(t==='splitnew')ok=ok&&c.join(',')!==task.initial.join(',');}else if(t==='open')ok=b.goal.includes(c[1]);else ok=Array.isArray(b.goal)&&c.length===b.goal.length&&c.every((n,i)=>n===b.goal[i]);
 if(!ok){incorrect(t==='stamp'?'印章和眼前要记录的数量还没对应':t==='hidden'?'光点和藏起来的那部分还没对应':t==='relation'?'路牌要表示两边实际的多少':t==='splitnew'?'两边都要有灯，而且要和上一次分法不同':'再看看每一边需要多少，移动后检查');return;}
 if(t==='hidden')world.reveal();let text=b.explain;if(['split','splitnew'].includes(t))text=`珞伊摆出了 ${c[0]} 和 ${c[1]}，合起来还是 5。`;if(t==='open')text=`珞伊选了 ${c[1]} 颗，比 3 多，演出就按这个数量布置。`;success(text);
}
function success(text,count=true){stopAudio();if(count)record('完成',`${task.hints||task.wrong?'提示或重试后完成':'独立完成'}；${text}`);phase='reward';$('controls').replaceChildren();$('access').hidden=true;$('help').hidden=true;$('replay').hidden=true;$('heading').textContent='珞伊，故事有了新变化';$('line').textContent=text;$('tip').textContent='';setMessage('');rewardAt=performance.now()+2600;}
function advance(){if(paused)return;generation++;stopAudio();beat++;showBeat();}
function finish(){phase='finish';stopAudio();save.episodes[ep.id]={beat:ep.beats.length-1,done:true};persist();world.celebrate();$('who').textContent='珞伊的巡演手记';$('heading').textContent='这一站，收好啦';$('line').textContent='珞伊和朋友完成了今天的演出。放下屏幕，看看远处吧。';$('tip').textContent='下一集留到你想玩的时候。';$('controls').replaceChildren();$('access').hidden=true;$('help').hidden=true;$('replay').hidden=true;control('收好，回到分集',showMenu,true,'finish');control('看看学习手记',openReport,false,'report-finish');}
function reportText(){const lines=['珞伊的数学故事手记',new Date().toLocaleString('zh-CN'),'人教版2024修订·一年级上册。本集选练，非整册覆盖。',''];for(const p of EPISODES){const events=save.events.filter(e=>e.episode===p.id),done=events.filter(e=>e.kind==='完成');if(!events.length&&!save.episodes[p.id])continue;lines.push(`${p.title}｜${p.extra?'拓展，不作课内要求':p.lesson+' 第'+p.pages+'页'}`);const last=new Map(done.map(e=>[e.task,e]));for(const e of last.values())lines.push('  '+e.detail);if(!last.size)lines.push('  已进入，尚无已完成操作。');lines.push('  本集边界：'+p.check,'');}lines.push('家长补充：'+(save.note||'暂无'),'','只记录本浏览器的可见操作；重试或提示后完成单独记录。通关不等于掌握，不据此评定智力或注意力。纸笔书写与口头解释需另行观察。','报告不会自动发送老师或 Codex，也不自动跨设备同步。人物对白为原创故事，不代表真实教师意见。');return lines.join('\n');}
function download(name,data,type){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function openReport(){modalResume=!paused&&phase!=='menu';pause();$('report-text').textContent=reportText();$('note').value=save.note;$('report-dialog').showModal();}
function closeReport(){$('report-dialog').close();if(modalResume)resume();}
function mount(){root=document.createElement('section');root.id='journey';root.innerHTML=`<div class="j-shell"><div class="j-top"><img src="assets/qingting-badge-original.jpg" alt="蜻蜓中队原班徽"><div><small>珞伊的蜻蜓剧场</small><b>森林巡演记</b></div><button id="j-pause" hidden>暂停</button><button id="j-report">手记</button><button id="j-back">返回</button></div><div id="j-lesson" class="j-lesson"></div><div id="j-menu" class="j-menu"><div class="j-intro"><span>数学 · 连续故事</span><h1>珞伊，<br>小剧场出发啦。</h1><p>把演出送进森林。<br>朋友自动讲故事，需要帮忙时由你动手。</p></div><div id="j-cards"></div><button id="j-prologue" class="j-prologue">回看序章：月亮怎么长脚了？</button><p class="j-boundary">正篇 10 集 · 第12—33页选练<br>两集自愿拓展，一次选一集就好。</p></div><div id="j-play" class="j-play" hidden><div class="j-location"><span id="j-place"></span><small id="j-step"></small></div><div id="j-canvas" aria-label="珞伊亲手操作的三维巡演场景"></div><div class="j-panel"><span id="j-who"></span><h2 id="j-heading"></h2><p id="j-line"></p><p id="j-tip"></p><div id="j-controls"></div><p id="j-message" role="status"></p><div class="j-tools"><button id="j-replay">再听一次</button><button id="j-help" hidden>请伙伴提示</button><button id="j-audio" class="j-primary" hidden>播放声音</button></div><details id="j-access" hidden><summary>需要更大的操作按钮</summary><div id="j-access-buttons"></div></details></div></div></div><dialog id="j-report-dialog" class="j-dialog"><div class="j-dialog-head"><h2>珞伊的学习手记</h2><button id="j-report-close" aria-label="关闭手记">×</button></div><pre id="j-report-text"></pre><label for="j-note">家长补一句观察</label><textarea id="j-note" maxlength="600" rows="3"></textarea><div class="j-row"><button id="j-save-report" class="j-primary">保存报告</button><button id="j-copy">复制报告</button></div><p id="j-report-status" role="status"></p><details><summary>进度与素材说明</summary><p>报告只存本浏览器。可导出并带到另一台设备；导入会替换本机数学巡演进度。</p><button id="j-export">导出进度</button><label>导入自己的进度<input id="j-import" type="file" accept=".json,application/json"></label><p>角色与对白为虚构创作；三维人物源自 Spring Rig（Blender Foundation / Blender Studio，CC BY 4.0），已修改。声音由本机离线语音合成，男、女角色分配不同音色，不是真人录音。</p><a href="assets/cinema/ATTRIBUTION.txt" target="_blank" rel="noopener">素材署名</a></details></dialog>`;document.body.append(root);
 $('back').onclick=()=>{if(phase==='menu'){root.hidden=true;document.getElementById('app').hidden=false;onClose?.();}else showMenu();};$('pause').onclick=()=>paused?resume():pause();$('report').onclick=openReport;$('report-close').onclick=closeReport;$('report-dialog').addEventListener('cancel',e=>{e.preventDefault();closeReport();});$('note').oninput=()=>{save.note=$('note').value;persist();};$('save-report').onclick=()=>download('珞伊数学故事手记.txt',reportText(),'text/plain;charset=utf-8');$('copy').onclick=async()=>{try{await navigator.clipboard.writeText(reportText());$('report-status').textContent='已复制，可以由家长发给老师。';}catch{$('report-status').textContent='复制受浏览器限制，请点保存报告。';}};$('export').onclick=()=>download('珞伊数学巡演进度.json',JSON.stringify(save,null,2),'application/json');$('import').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{if(f.size>1e6)throw Error('过大');const incoming=valid(JSON.parse(await f.text()));if(!confirm('用这份文件替换本浏览器的数学巡演进度？'))return;save=incoming;persist();modalResume=false;$('report-dialog').close();showMenu();}catch{$('report-status').textContent='没有导入：文件格式或内容不符合，原进度保留。';}finally{e.target.value='';}};$('prologue').onclick=()=>{showMenu();root.hidden=true;document.getElementById('app').hidden=false;prologue?.();};$('audio').onclick=()=>cue?playAudio():speak();$('replay').onclick=()=>{if(ep){record('重听');speak();}};$('help').onclick=()=>{if(!task)return;task.hints++;record('提示',task.data.explain);setMessage(task.data.explain);};document.addEventListener('visibilitychange',()=>{if(document.hidden&&!root.hidden)pause();});window.journeyInspect=()=>({phase,episode:ep?.id,beat,paused,task:task?{id:task.data.id,type:task.data.type,hints:task.hints,wrong:task.wrong,points:task.points,round:task.round,matched:task.matched,selected:task.selected}:null,world:world?.inspect(),audio:{time:audio.currentTime,paused:audio.paused,done:audioDone,cue:cue?{start:cue.start,duration:cue.duration}:null},events:save.events});
}
export function openJourney(options={}){onClose=options.onClose;prologue=options.prologue;if(!root){mount();audio.hidden=true;root.append(audio);}document.getElementById('app').hidden=true;root.hidden=false;showMenu();if(options.report)openReport();}
