import * as T from './vendor/three.module.js';
import {GLTFLoader} from './vendor/loaders/GLTFLoader.js';
import {StoryStage} from './cinema-world.js';

// The same approved character meshes, with baked facial and hand deformations.
export class JourneyWorld extends StoryStage {
 constructor(host,pick){super(host,pick);this.actors=new Map();this.camTo=new T.Vector3(0,2.8,6.3);this.lookTo=new T.Vector3(0,1,-1);this.look=new T.Vector3(0,1,-1);this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.onFrame=()=>{};this.active=true;this.observer=new ResizeObserver(()=>{if(host.clientHeight>0)this.resize();});this.observer.observe(host);}
 async loadCast(keys=[]){this.cast??=new Map();this.castLoads??=new Map();const loader=new GLTFLoader();const loads=['girl','friend','brother','tang',...keys].map(key=>{if(this.cast.has(key))return Promise.resolve();if(!this.castLoads.has(key))this.castLoads.set(key,loader.loadAsync(`assets/cinema/actor-live-${key}.glb`).then(d=>this.cast.set(key,d.scene)).catch(e=>{this.castLoads.delete(key);throw e;}));return this.castLoads.get(key);});if(!this.forestLoad)this.forestLoad=loader.loadAsync('assets/cinema/journey-forest.glb').then(d=>this.forest=d.scene).catch(e=>{this.forestLoad=null;throw e;});return Promise.all([...loads,this.forestLoad]);}
 character(key,pos){const g=new T.Group();g.position.set(...pos);this.root.add(g);const model=this.cast.get(key).clone(true);const box=new T.Box3().setFromObject(model),size=box.getSize(new T.Vector3()),center=box.getCenter(new T.Vector3()),scale=(['wang','li'].includes(key)?2.5:key==='brother'?2.08:key==='tang'?1.73:1.85)/size.y;model.scale.setScalar(scale);model.position.set(-center.x*scale,-box.min.y*scale,-center.z*scale);g.add(model);const morphs=[];model.traverse(o=>{if(!o.isMesh)return;o.userData.sharedCast=true;o.castShadow=true;if(o.morphTargetInfluences)morphs.push(o);});this.actors.set(key,{g,model,morphs,base:g.position.clone()});return g;}
 squirrel(){const g=new T.Group();g.position.set(0,.55,-2.6);this.root.add(g);this.ell([0,.4,0],[.28,.40,.24],'#ad6c35',g);this.ell([0,.45,.19],[.18,.27,.07],'#f0cf93',g);this.ell([0,.92,0],[.32,.28,.26],'#b77c42',g);for(const x of [-.22,.22]){this.ell([x,1.17,0],[.09,.18,.075],'#91552f',g);this.ell([x*.72,.97,.235],[.052,.067,.029],'#1e2f2c',g);this.ell([x*.72-.012,1.0,.26],[.016,.020,.01],'#fff3d9',g);}this.ell([0,.87,.26],[.10,.07,.07],'#f4d7a1',g);this.ell([0,.92,.32],[.04,.03,.02],'#33332b',g);const mouth=this.ell([0,.83,.309],[.04,.008,.018],'#493323',g);this.ell([.34,.52,-.18],[.23,.49,.26],'#93532b',g).rotation.z=-.4;this.ell([.35,.85,-.1],[.18,.27,.19],'#b57e47',g);for(const x of [-.17,.17])this.ell([x,.04,.12],[.11,.06,.20],'#764329',g);this.actors.set('squirrel',{g,base:g.position.clone(),mouth,morphs:[]});}
 tree(x,z,height=3.3,pink=false){const trunk=this.mesh(new T.CylinderGeometry(.14,.24,height,10),'#7b6244');trunk.position.set(x,height/2,z);for(let i=0;i<3;i++)this.ell([x+(i-1)*.48,height-.2+(i%2)*.65,z],[.88,.85,.8],pink?'#d89f9a':i%2?'#769b73':'#567d60');}
 build(ep){super.reset('journey');this.ep=ep;this.actors.clear();this.targets=[];this.byId.clear();this.root.children[0].scale.set(3,1,3);this.root.children[0].material.color.set('#c5c69c');const night=['night','festival','hill'].includes(ep.theme);const sky=night?'#4c6875':'#b5d1cb';this.scene.background=new T.Color(sky);this.scene.fog=new T.Fog(sky,15,29);this.decor=[];this.props=[];this.trays=[];this.taskRoot=new T.Group();this.root.add(this.taskRoot);
  const grove=this.forest.clone(true);grove.scale.setScalar(1.7);grove.position.set(0,-.11,-2.8);grove.traverse(o=>{if(o.isMesh){o.userData.sharedCast=true;o.castShadow=true;o.receiveShadow=true;}});this.root.add(grove);
  for(let i=0;i<28;i++){const x=Math.sin(i*3.9)*(4+i%3),z=Math.cos(i*2.7)*5-1;if(Math.abs(x)<2)continue;this.ell([x,.03,z],[.13,.08,.13],i%2?'#f4c66e':'#e5abaf');}
  if(['pond','river'].includes(ep.theme)){const water=this.mesh(new T.PlaneGeometry(5,13),new T.MeshStandardMaterial({color:'#64acae',roughness:.25,metalness:.15}));water.rotation.x=-Math.PI/2;water.position.set(-4.7,-.05,-2);for(let i=0;i<6;i++){const leaf=this.mesh(new T.CylinderGeometry(.4,.4,.025,24),'#6caa7d');leaf.position.set(-3.1-i%2,.01,-i*1.3);}}
  if(ep.theme==='bamboo'){for(let i=0;i<12;i++){const x=(i%2?1:-1)*(2.7+i%3*.2),z=-2.6-Math.floor(i/2)*.6;const stem=this.mesh(new T.CylinderGeometry(.065,.085,4.2,8),'#8baa67');stem.position.set(x,2.1,z);for(let j=1;j<5;j++)this.ell([x+.16,j*.7,z],[.32,.045,.07],'#638e63').rotation.z=.4;}}
  if(['windmill','river'].includes(ep.theme)){const tower=this.mesh(new T.CylinderGeometry(.43,.73,2.5,8),'#d7b681');tower.position.set(-2.8,1.1,-4.8);const wheel=new T.Group();wheel.position.set(-2.8,2.8,-4.35);this.root.add(wheel);for(let i=0;i<4;i++){const blade=this.mesh(new T.BoxGeometry(.27,1.9,.065),'#f0d8a1',wheel);blade.position.set(Math.sin(i*Math.PI/2)*.6,Math.cos(i*Math.PI/2)*.6,0);blade.rotation.z=-i*Math.PI/2;}this.decor.push({o:wheel,spin:true});}
  if(ep.theme==='rain'){const hut=this.mesh(new T.BoxGeometry(3,1.9,1.7),'#a37e53');hut.position.set(0,1.6,-5);const roof=this.mesh(new T.ConeGeometry(2.6,1,4),'#597d68');roof.position.set(0,3,-5);roof.rotation.y=Math.PI/4;for(let i=0;i<25;i++){const drop=this.mesh(new T.CylinderGeometry(.008,.008,.14,4),'#e0eded');drop.position.set(Math.sin(i)*5,1+i%4,-3-i%5);this.decor.push({o:drop,rain:true});}}
  // A travelling theatre, with the original class emblem attached to its canvas.
  const cart=this.mesh(new T.BoxGeometry(1.9,.52,1.05),'#638d80');cart.position.set(2.35,.45,-3.7);for(const x of [1.65,3.05]){const wheel=this.mesh(new T.CylinderGeometry(.30,.30,.13,24),'#795d42');wheel.rotation.x=Math.PI/2;wheel.position.set(x,.20,-3.10);}const awning=this.mesh(new T.CylinderGeometry(.64,.64,2,24,1,false,0,Math.PI),'#e3bc83');awning.rotation.z=Math.PI/2;awning.position.set(2.35,1.36,-3.65);
  const badge=new T.Mesh(new T.PlaneGeometry(.57,.57),new T.MeshBasicMaterial({map:this.textures.load('assets/qingting-badge-original.jpg'),side:T.DoubleSide}));badge.position.set(2.35,.69,-3.155);this.root.add(badge);
  this.character('friend',[-1.45,0,-2.05]);this.character('girl',[1.45,0,-2.05]);this.character('brother',[-2.75,0,-3.1]);this.character('tang',[2.65,0,-2.7]);this.squirrel();for(const key of ['wang','li'])if(ep.beats.some(b=>b.who===key)){const g=this.character(key,[0,0,-3.9]);g.visible=false;}
  if(night){const moon=this.ell([1.6,4.4,-9],[.60,.60,.18],new T.MeshBasicMaterial({color:'#ffe7a3'}));this.decor.push({o:moon,float:true});for(let i=0;i<14;i++){const p=this.ell([Math.sin(i*2)*4,1+(i%3)*.5,-3+Math.cos(i)*3],[.025,.025,.025],new T.MeshBasicMaterial({color:'#ffdb7f'}));this.decor.push({o:p,float:true});}}
  if(ep.theme==='festival'){for(const x of [-2.6,2.6]){const curtain=this.mesh(new T.BoxGeometry(.55,2.5,.14),'#b46a78');curtain.position.set(x,1.4,-3.7);}const beam=this.mesh(new T.BoxGeometry(5.5,.22,.25),'#d9ad68');beam.position.set(0,2.8,-3.7);}
  this.table=this.mesh(new T.CylinderGeometry(2.35,2.4,.18,64),'#e6cca1',this.taskRoot);this.table.position.set(0,.03,.75);this.table.visible=false;this.shot('wide');
 }
 shot(who,action='talk'){this.speaker=who;this.action=action;this.talkLevel=0;this.taskRoot.visible=false;const teacher=['wang','li'].includes(who);for(const [key,a]of this.actors)a.g.visible=teacher?key===who:!['wang','li'].includes(key);const a=this.actors.get(who);if(a){if(teacher){this.camTo.set(.25,2.2,-.7);this.lookTo.set(0,1.85,-3.9);}else if(who==='squirrel'){this.camTo.set(.25,1.6,.5);this.lookTo.set(0,1.3,-2.6);}else{this.camTo.set(a.base.x*.90,1.72,.85);this.lookTo.set(a.base.x*.95,1.26,a.base.z);}}else{this.camTo.set(0,2.6,6.0);this.lookTo.set(0,1,-1.8);}if(action==='celebrate'||action==='depart'||action==='curtain'){this.camTo.set(0,2.8,6.8);this.lookTo.set(0,.9,-2);}if(this.reduced){this.camera.position.copy(this.camTo);this.look.copy(this.lookTo);}}
 demonstrate(action){if(action==='spread'&&this.props?.length){const who=this.speaker;this.taskView();this.speaker=who;for(let i=0;i<this.counts.length;i++){const list=this.props.filter(p=>p.userData.group===i),c=this.slots[i];list.forEach((p,j)=>this.move(p.userData.id,[c[0]+(j-(list.length-1)/2)*.42,c[1]+.1,c[2]-.1]));}}else if(action==='swap'&&this.counts?.length===2){const who=this.speaker;this.groups([...this.counts].reverse());this.speaker=who;}else if(action==='equal'){const who=this.speaker;this.groups([4,4]);this.speaker=who;}else if(action==='cover'){const who=this.speaker;this.groups([2,3],{hidden:1});this.speaker=who;}}
 taskView(){this.speaker=null;for(const [key,a]of this.actors)a.g.visible=!['wang','li'].includes(key);this.taskRoot.visible=true;this.table.visible=true;this.camTo.set(0,4.2,4.4);this.lookTo.set(0,.2,.55);this.camera.position.copy(this.camTo);this.look.copy(this.lookTo);this.camera.lookAt(this.look);}
 clearTask(){for(const o of [...this.taskRoot.children])if(o!==this.table){o.traverse(m=>{if(m.isMesh){m.geometry.dispose();for(const mat of Array.isArray(m.material)?m.material:[m.material]){mat.map?.dispose();mat.dispose();}}});this.taskRoot.remove(o);}this.targets=[];this.byId.clear();this.props=[];this.trays=[];this.cancelMoves();}
 target(id,pos,parent=this.taskRoot){const o=new T.Group();o.position.set(...pos);o.userData.id=id;parent.add(o);this.targets.push(o);this.byId.set(id,o);if(id.startsWith('prop-')){const hit=new T.Mesh(new T.PlaneGeometry(.50,.55),new T.MeshBasicMaterial({transparent:true,opacity:0,depthWrite:false,side:T.DoubleSide}));hit.position.set(0,.28,.04);hit.userData.billboard=true;hit.userData.hit=true;o.add(hit);}return o;}
 shape(kind,g,color='#efc45f'){const mat=this.mat(color);if(kind==='lamp'){this.mesh(new T.CylinderGeometry(.19,.21,.40,16),mat,g).position.y=.24;const top=this.mesh(new T.ConeGeometry(.25,.12,12),'#95714a',g);top.position.y=.5;this.mesh(new T.TorusGeometry(.09,.018,8,20),this.mat('#917451'),g).position.set(0,.60,0);}else if(kind==='hat'){this.mesh(new T.CylinderGeometry(.30,.30,.045,24),mat,g).position.y=.1;this.mesh(new T.ConeGeometry(.23,.3,24),mat,g).position.y=.25;}else if(kind==='box'){this.mesh(new T.BoxGeometry(.38,.4,.34),mat,g).position.y=.24;this.mesh(new T.BoxGeometry(.41,.06,.38),'#936c48',g).position.y=.44;}else if(kind==='clip'){const o=this.mesh(new T.BoxGeometry(.13,.42,.13),mat,g);o.position.y=.24;o.rotation.z=.22;this.mesh(new T.TorusGeometry(.069,.02,8,16),'#937252',g).position.set(0,.27,.075);}else if(kind==='ticket'){const m=this.mesh(new T.BoxGeometry(.32,.04,.42),mat,g);m.position.y=.09;const strip=this.mesh(new T.BoxGeometry(.23,.012,.055),'#88653e',g);strip.position.set(0,.119,.05);}else if(kind==='star'){const s=new T.Shape();for(let i=0;i<10;i++){const r=i%2?.13:.29,a=i*Math.PI/5;const x=Math.sin(a)*r,y=Math.cos(a)*r;i?s.lineTo(x,y):s.moveTo(x,y);}s.closePath();const o=this.mesh(new T.ExtrudeGeometry(s,{depth:.07,bevelEnabled:true,bevelSegments:1,steps:1,bevelSize:.015,bevelThickness:.015}),mat,g);o.rotation.x=-Math.PI/2;o.position.y=.15;}else if(kind==='bun'){this.ell([0,.17,0],[.23,.16,.22],'#f1d7a7',g);for(let i=0;i<3;i++)this.tube([[-.13,.28,(i-1)*.07],[0,.34,(i-1)*.07],[.13,.28,(i-1)*.07]],.011,'#cdb07b',g);}else{this.mesh(new T.CylinderGeometry(.23,.23,.26,20),mat,g).position.y=.20;this.mesh(new T.CylinderGeometry(.235,.235,.024,20),'#f4dec0',g).position.y=.35;}}
 layout(n){if(n===1)return [[0,.15,.7]];if(n===2)return [[-1.05,.15,.7],[1.05,.15,.7]];if(n===3)return [[-1.15,.15,.05],[1.15,.15,.05],[0,.15,1.65]];if(n===4)return [[0,.15,1.85],[-1.45,.15,-.05],[0,.15,-.05],[1.45,.15,-.05]];return Array.from({length:n},(_,i)=>[(i-(n-1)/2)*.78,.15,.65]);}
 groups(counts,{labels=[],kind=this.ep.prop,hidden=-1}={}){this.clearTask();this.taskView();this.counts=[...counts];this.slots=this.layout(counts.length);counts.forEach((n,i)=>{const g=this.target('tray-'+i,this.slots[i]);this.trays.push(g);const plate=this.mesh(new T.CylinderGeometry(counts.length>3?.65:.86,counts.length>3?.7:.93,.10,48),i%2?'#a4bab3':'#d6bca2',g);plate.position.y=-.04;if(labels[i]){const label=this.label(labels[i],'',counts.length>3?.85:1.16,.28);label.position.set(0,.04,.65);g.add(label);}for(let j=0;j<n;j++){const p=this.target(`prop-${i}-${j}`,[0,0,0]);p.userData.group=i;p.userData.slot=j;this.shape(kind,p,i%2?'#e9b967':'#e3b181');this.props.push(p);}if(hidden===i){const c=this.target('cover',[...this.slots[i]]);this.mesh(new T.CylinderGeometry(.72,.84,.43,40),'#91b1ab',c).position.y=.21;this.plaque(c,'？','',.5,.45).position.set(0,.63,0);}});this.arrange(false);if(hidden>=0)for(const p of this.props)if(p.userData.group===hidden)p.visible=false;}
 propSpot(group,index,count){const center=this.slots[group];const columns=count>4?3:2;const row=Math.floor(index/columns),cols=Math.min(count,columns);return [center[0]+(index%columns-(cols-1)/2)*.55,center[1]+.07,center[2]+(row-(Math.ceil(count/columns)-1)/2)*.55-.13];}
 arrange(animate=true){for(let i=0;i<this.counts.length;i++){const list=this.props.filter(p=>p.userData.group===i);list.forEach((p,j)=>{const pos=this.propSpot(i,j,list.length);if(animate)this.move(p.userData.id,pos);else p.position.set(...pos);});}}
 transfer(id,to){const p=this.byId.get(id);if(!p||p.userData.group===to)return false;const from=p.userData.group;this.counts[from]--;this.counts[to]++;p.userData.group=to;this.arrange();this.select(null);return true;}
 select(id){this.selected=id;for(const p of this.props){p.scale.setScalar(p.userData.id===id?1.18:1);p.traverse(m=>{if(m.isMesh&&m.material.emissive){m.material.emissive.set(p.userData.id===id?'#c38b22':'#000000');m.material.emissiveIntensity=.22;}});}}
 reveal(){const c=this.byId.get('cover');if(c)c.visible=false;for(const p of this.props)p.visible=true;}
 sign(text){let g=this.byId.get('sign');if(g){g.traverse(m=>{m.geometry?.dispose();for(const mat of Array.isArray(m.material)?m.material:[m.material]){mat?.map?.dispose();mat?.dispose();}});g.clear();}else g=this.target('sign',[0,.6,-.4]);this.plaque(g,text,'',.66,.57);}
 ducks(){for(let i=0;i<4;i++){const p=this.propSpot(1,i,4),g=this.target('duck-'+i,[p[0],p[1]-.02,p[2]]);this.ell([0,.11,0],[.19,.16,.18],'#edcf78',g);this.ell([0,.28,.05],[.14,.13,.12],'#f1d786',g);this.ell([0,.25,.17],[.09,.035,.065],'#c77d3f',g);for(const x of [-.06,.06])this.ell([x,.31,.14],[.017,.022,.016],'#293b34',g);}}
 hatOn(id,duck){const p=this.byId.get(id),to=this.propSpot(1,duck,4);p.userData.group=1;this.counts[0]--;this.counts[1]++;to[1]+=.38;this.move(id,to);this.select(null);}
 extraHat(){const g=this.target('prop-extra',[-1.05,.22,.55]);g.userData.group=0;this.shape('hat',g,'#8fb2a0');this.props.push(g);this.counts[0]++;}
 pair(a,b){for(const id of [a,b]){const p=this.byId.get(id);p.userData.paired=true;this.glow(id);}const aP=this.byId.get(a).position,bP=this.byId.get(b).position;const line=this.tube([[aP.x,.42,aP.z],[0,.65,(aP.z+bP.z)/2],[bP.x,.42,bP.z]],.022,'#497b72',this.taskRoot);line.userData.link=true;}
 mail(){this.clearTask();this.taskView();this.slots=this.layout(5);for(let i=0;i<5;i++){const g=this.target('box-'+i,this.slots[i]);this.shape('box',g,i%2?'#a5b9b9':'#d5a775');g.scale.setScalar(1.35);}const flag=this.target('flag',[-2.1,.2,-.05]);this.mesh(new T.CylinderGeometry(.025,.025,.9,8),'#8a7145',flag).position.y=.4;this.mesh(new T.PlaneGeometry(.35,.22),new T.MeshBasicMaterial({map:this.textures.load('assets/qingting-badge-original.jpg'),side:T.DoubleSide}),flag).position.set(.14,.7,0);}
 celebrate(choice){this.choice=choice;this.shot('wide','celebrate');for(const a of this.actors.values())a.party=true;if(choice){const g=new T.Group();g.position.set(0,1.6,-1);this.root.add(g);if(choice==='dragonfly'){this.ell([0,0,0],[.06,.4,.07],'#6ba095',g);for(const x of [-1,1])for(const y of [-.1,.15])this.ell([x*.22,y,0],[.27,.08,.035],'#b9daca',g);}else{this.ell([0,0,0],[.26,.26,.1],'#f5dfb0',g);for(const x of [-.13,.13])this.ell([x,.34,0],[.085,.23,.075],'#f5dfb0',g);}this.decor.push({o:g,float:true});}}
 render(){requestAnimationFrame(this.render);const dt=Math.min(this.clock.getDelta(),.15);if(!this.active||!this.camTo)return;const fov=this.taskRoot?.visible?Math.min(65,2*Math.atan(4.6/(2*this.camTo.distanceTo(this.lookTo)*this.camera.aspect))*180/Math.PI):42;this.camera.fov=fov;this.camera.updateProjectionMatrix();if(!this.paused){this.time+=dt;this.onFrame?.();const speed=this.reduced?1:Math.min(1,dt*3);this.camera.position.lerp(this.camTo,speed);this.look.lerp(this.lookTo,speed);this.camera.lookAt(this.look);for(const [key,a]of this.actors){const speaking=key===this.speaker;const blink=Math.max(0,1-Math.abs(((this.time+key.length*.43)%4.3)-.12)/.12);for(const m of a.morphs){const d=m.morphTargetDictionary;m.morphTargetInfluences[d.speak]=speaking?Math.max(0,Math.min(1,this.talkLevel||0)):0;m.morphTargetInfluences[d.blink]=blink;m.morphTargetInfluences[d.gesture]=speaking?.25+.2*Math.sin(this.time*2):0;}if(a.mouth)a.mouth.scale.y=.008*(speaking?1+(this.talkLevel||0)*6:1);a.g.rotation.y=Math.sin(this.time*.9+key.length)*.025;a.g.position.y=a.base.y+(a.party?Math.abs(Math.sin(this.time*3))*.10:Math.sin(this.time*1.5)*.009);}for(const d of this.decor||[]){if(d.spin)d.o.rotation.z+=dt*.23;if(d.rain){d.o.position.y-=dt*2;if(d.o.position.y<.1)d.o.position.y=4;}if(d.float)d.o.position.y+=Math.sin(this.time*2+d.o.position.x)*dt*.06;}for(let i=this.animations.length-1;i>=0;i--){const a=this.animations[i];a.t+=dt;const u=Math.min(1,a.t/a.d),e=u*u*(3-2*u);a.o.position.lerpVectors(a.from,a.to,e);a.o.position.y+=Math.sin(u*Math.PI)*.35;if(u===1){this.animations.splice(i,1);a.resolve();}}}this.root.traverse(o=>{if(o.userData.billboard)o.quaternion.copy(this.camera.quaternion);});this.renderer.render(this.scene,this.camera);}
 positions(){const bounds=this.host.getBoundingClientRect();return Object.fromEntries([...this.byId].map(([id,o])=>{let v=new T.Vector3();const hit=o.children.find(m=>m.userData.hit);if(id.startsWith('tray-'))o.localToWorld(v.set(0,.08,.65));else if(hit)hit.getWorldPosition(v);else{const box=new T.Box3().setFromObject(o);box.getCenter(v);}v.project(this.camera);return [id,{x:bounds.left+(v.x*.5+.5)*bounds.width,y:bounds.top+(-v.y*.5+.5)*bounds.height}];}));}
 inspect(){return {positions:this.positions(),counts:this.counts,props:(this.props||[]).map(p=>({id:p.userData.id,group:p.userData.group})),selected:this.selected,actors:[...this.actors].map(([key,a])=>({key,mouth:a.morphs[0]?.morphTargetInfluences?.[0]||0,morphs:a.morphs.length})),camera:this.camera.position.toArray()};}
}
