import {PILOTS,PEOPLE,PILOT_VERSION} from './pilot-data.js?v=pilot1';
import {PilotWorld} from './pilot-world.js?v=pilot1';
const $=id=>document.getElementById(id),audio=$('voice'),KEY='luoyi-pilots-v1',py={天:'tiān',地:'dì',人:'rén',我:'wǒ',你:'nǐ',他:'tā'};
const blank=()=>({version:1,math:{index:0,done:false,events:[]},chinese:{index:0,done:false,events:[]},oral:'未观察',note:''});
let save;try{const d=JSON.parse(localStorage.getItem(KEY));if(d.version!==1||!['math','chinese'].every(k=>Number.isInteger(d[k]?.index)&&d[k].index>=0&&d[k].index<PILOTS[k].beats.length&&Array.isArray(d[k].events)&&d[k].events.length<=1500))throw Error();save=d;}catch{save=blank();}
let world,manifest,ep,index=0,phase='home',task,step=0,token=0,locked=false,paused=false,cue=null,resolveAudio,afterRetry,loadingSubject,noticeTimer,pendingAdvance=false;
function persist(){try{localStorage.setItem(KEY,JSON.stringify(save));}catch{notice('浏览器未能保存，请在家长手记保存报告。');}}
function event(kind,more={}){if(!ep)return;save[ep.id].events.push({time:new Date().toISOString(),beat:ep.beats[index]?.id,kind,...more});save[ep.id].events=save[ep.id].events.slice(-1500);persist();}
function notice(s){$('notice').textContent=s;$('notice').classList.add('show');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('notice').classList.remove('show'),2200);}
function stopAudio(){audio.pause();resolveAudio?.(false);resolveAudio=null;afterRetry=null;cue=null;$('audio-retry').hidden=true;if(world){world.speaker=null;world.level=0;}}
function play(id){stopAudio();const c=manifest.lines[id];if(!c){notice('这一句声音还没准备好，请稍后重试。');return Promise.resolve(false);}cue=c;audio.src='assets/pilot/'+c.file+'?v='+PILOT_VERSION;world.speaker=c.who;world.level=0;return new Promise(resolve=>{resolveAudio=resolve;audio.onended=()=>{world.level=0;world.speaker=null;resolveAudio=null;resolve(true);};audio.onerror=()=>{$('audio-retry').textContent='声音没加载好，点一下重试';$('audio-retry').hidden=false;afterRetry=()=>{audio.load();return audio.play();};};afterRetry=()=>audio.play();audio.play().then(()=>{$('audio-retry').hidden=true;}).catch(()=>{$('audio-retry').textContent='点一下，听朋友说话';$('audio-retry').hidden=false;});});}
$('audio-retry').onclick=async()=>{try{await afterRetry?.();$('audio-retry').hidden=true;}catch{notice('请检查网络后再试一下。');}};
function ensureWorld(){if(world)return;world=new PilotWorld($('world'),pick);world.onFrame=()=>{if(cue&&!audio.paused&&audio.currentTime>=cue.introDuration){const n=Math.floor(audio.currentTime/.04);world.level=cue.envelope[n]||0;}else world.level=0;};}
async function start(subject){const mine=++token;pendingAdvance=false;loadingSubject=subject;phase='loading';$('loading').hidden=false;$('loading-message').textContent='朋友正在走进画面…';$('retry-load').hidden=true;$('home').hidden=true;try{ensureWorld();world.active=true;world.paused=false;await Promise.all([world.load(PILOTS[subject]),manifest?Promise.resolve():fetch('assets/pilot/voices.json?v='+PILOT_VERSION).then(r=>{if(!r.ok)throw Error('voices');return r.json();}).then(d=>manifest=d)]);if(mine!==token)return;ep=PILOTS[subject];index=save[subject].done?0:save[subject].index;world.build(ep);$('loading').hidden=true;$('hud').hidden=false;$('pause').hidden=false;$('lesson').textContent=`${ep.subject}｜${ep.lesson} · 第${ep.pages}页${subject==='math'?'选练':''}`;event('进入故事');show();}catch(e){console.error(e);if(mine!==token)return;$('loading-message').textContent='画面还没加载好，联网后再试一下。';$('retry-load').hidden=false;}}
function ruby(el,text,phonetic){el.replaceChildren();const r=document.createElement('ruby');r.append(document.createTextNode(text));const rt=document.createElement('rt');rt.textContent=phonetic;r.append(rt);el.append(r);}
function instructions(b){$('instruction').hidden=!b;$('help').hidden=!b;$('pilot-app').classList.toggle('task',!!b);if(!b){$('letter').hidden=true;return;}const r=$('instruction-ruby');r.querySelector('span').textContent=b.kind==='pronoun'?'点收信的人':b.kind==='receive'?'点一下，收好信':b.title;r.querySelector('rt').textContent=b.kind==='pronoun'?'diǎn shōu xìn de rén':b.kind==='receive'?'diǎn yí xià shōu hǎo xìn':b.py;const word=b.kind==='mail'?b.goal[step]:['pronoun','receive'].includes(b.kind)?b.title:null;$('letter').hidden=!word;if(word)ruby($('letter'),word,py[word]);}
async function show(){const mine=++token;stopAudio();paused=false;world.paused=false;locked=true;task=null;step=0;const b=ep.beats[index];save[ep.id].index=index;persist();phase='talk';$('progress').textContent=`${index+1} / ${ep.beats.length}`;$('speaker').textContent=PEOPLE[b.who].name+'说';$('dialogue').textContent=b.text;instructions(null);world.beat(b);
 if(b.kind){task=b;world.setup(b);instructions(b);$('pilot-app').classList.remove('task');}
 const ok=await play(b.id);if(mine!==token||!ok)return;
 if(b.kind){phase='task';locked=false;$('pilot-app').classList.add('task');if(b.kind==='seals')await sealPrompt(mine);}else{await new Promise(r=>setTimeout(r,240));if(mine===token&&!paused)next();}
}
async function sealPrompt(mine=token){locked=true;const target=task.goal[step];await play('find-'+['天','地','人'].indexOf(target));if(mine===token)locked=false;}
function next(){if(paused){pendingAdvance=true;return;}pendingAdvance=false;if(index+1>=ep.beats.length){completeEpisode();return;}index++;show();}
function countedTask(){return ['load','return','add'].includes(task?.kind);}
async function pick(id){if(phase!=='task'||paused||locked||!task)return;locked=true;const mine=token,b=task;let correct=false;
 if(countedTask())correct=id.startsWith('lamp-');else if(b.kind==='bridge')correct=id==='bundle-'+b.goal;else if(b.kind==='mail'||b.kind==='seals')correct=id===b.goal[step];else if(b.kind==='pronoun')correct=id===b.goal;else if(b.kind==='receive')correct=id==='letter';
 event(correct?'操作':'需再试',{target:id,step});
 if(!correct){world.hint();const hint=b.kind==='bridge'?'hint-bridge':b.kind==='mail'?'hint-mail':b.kind==='seals'?'find-'+['天','地','人'].indexOf(b.goal[step]):'hint-pronoun';await play(hint);if(mine===token)locked=false;return;}
 if(countedTask()){step++;const n=b.kind==='add'?b.goal:step;await world.collect(id,n,b.goal);if(mine!==token)return;const goal=b.kind==='add'?1:b.goal;if(step<goal){locked=false;return;}world.tidyLamps();await play('count-'+n);}
 else if(b.kind==='bridge'){await world.fillBridge();await new Promise(r=>setTimeout(r,700));}
 else if(b.kind==='mail'||b.kind==='seals'){const found=b.goal[step];await world.reward(id);if(mine!==token)return;if(b.kind==='mail')await play('word-'+['天','地','人'].indexOf(found));step++;if(mine!==token)return;if(step<b.goal.length){world.setup(b,step);instructions(b);if(b.kind==='seals')await sealPrompt(mine);else locked=false;return;}}
 else{await world.reward(id);await new Promise(r=>setTimeout(r,350));}
 if(mine!==token)return;event('完成互动',{stage:b.stage,kindOfTask:b.kind});phase='transition';await new Promise(r=>setTimeout(r,400));if(mine===token)next();
}
async function help(){if(phase!=='task'||paused||locked)return;const mine=token;locked=true;event('使用提示');world.hint();let id=task.kind==='bridge'?'hint-bridge':task.kind==='mail'?'hint-mail':task.kind==='seals'?'find-'+['天','地','人'].indexOf(task.goal[step]):['pronoun','receive'].includes(task.kind)?'hint-pronoun':'hint-load';await play(id);if(mine===token)locked=false;}
function pause(){if(!ep||phase==='home'||phase==='loading'||paused)return;paused=true;world.paused=true;audio.pause();$('rest').showModal();}
function resume(){paused=false;world.paused=false;$('rest').close();if(pendingAdvance){next();return;}if(cue&&audio.currentTime<audio.duration-.08){audio.play().catch(()=>{$('audio-retry').hidden=false;});}else if(phase==='talk'){next();}}
function home(){++token;stopAudio();task=null;phase='home';paused=false;locked=false;if(world){world.paused=true;world.active=false;}$('home').hidden=false;$('hud').hidden=true;$('loading').hidden=true;$('pause').hidden=true;$('lesson').textContent='选择今天的故事';$('pilot-app').classList.remove('task');for(const id of ['rest','finish'])if($(id).open)$(id).close();}
async function completeEpisode(){phase='finish';task=null;instructions(null);save[ep.id].done=true;event('完成故事');$('finish-title').textContent=ep.id==='math'?'珞伊，小灯车出发啦！':'珞伊，信都送到啦！';$('finish-text').textContent=ep.oral;$('finish').showModal();await play('done-'+ep.id);}
function makeReport(){const lines=['珞伊的故事手记',new Date().toLocaleDateString('zh-CN'),''];for(const s of ['chinese','math']){const e=PILOTS[s],d=save[s];lines.push(`${e.subject}｜${e.title}`,`教材：${e.lesson} 第${e.pages}页${s==='math'?'选练':''}`,`故事状态：${d.done?'已看完':d.events.length?'进行中':'尚未开始'}`);for(const b of e.beats.filter(b=>b.kind)){const es=d.events.filter(x=>x.beat===b.id),done=es.some(x=>x.kind==='完成互动'),help=es.filter(x=>x.kind==='使用提示').length,wrong=es.filter(x=>x.kind==='需再试').length;let state=done?'完成':'未完成';const guided=b.stage==='guided'||['load','return','add'].includes(b.kind);if(done)state=help||wrong?'经提示或重试后完成':guided?'跟随情境引导完成':s==='chinese'?'无额外提示完成（有拼音支持）':'无额外提示选对';lines.push(`• ${b.title}：${state}${help||wrong?`；提示${help}次，再试${wrong}次（保留历次记录）`:''}`);}lines.push('覆盖边界：'+e.coverage,'');}lines.push('语文朗读：'+save.oral,'家长观察：'+(save.note||'未填写'),'','这些记录反映游戏中的表现，不等同于整课掌握、考试成绩或专注力测评。','记录只在当前浏览器；老师和 Codex 不会自动收到。');return lines.join('\n');}
function openReport(){if(phase!=='home'&&phase!=='finish'&&!paused)pause();$('observation').value=save.note;$('oral').value=save.oral;$('report').textContent=makeReport();$('parents').showModal();}
function saveObservation(){save.note=$('observation').value;save.oral=$('oral').value;persist();$('report').textContent=makeReport();}
document.querySelectorAll('[data-subject]').forEach(b=>b.onclick=()=>start(b.dataset.subject));$('pause').onclick=pause;$('resume').onclick=resume;$('back').onclick=home;$('loading-home').onclick=home;$('retry-load').onclick=()=>start(loadingSubject);$('finish-home').onclick=home;$('parent').onclick=openReport;$('finish-report').onclick=openReport;$('close-report').onclick=()=>{$('parents').close();};$('help').onclick=help;
$('listen').onclick=async()=>{if(paused||!ep)return;if(phase==='talk'&&cue){audio.currentTime=0;return;}if(locked)return;const mine=token;locked=true;if(task)event('重听要求');await play(task?.id||ep.beats[index].id);if(mine===token)locked=false;};
$('observation').onchange=saveObservation;$('oral').onchange=saveObservation;$('download').onclick=()=>{saveObservation();const blob=new Blob([makeReport()],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='珞伊的故事手记.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);$('report-status').textContent='报告已生成，可由家长发给老师或上传到对话。';};$('copy').onclick=async()=>{saveObservation();try{await navigator.clipboard.writeText(makeReport());$('report-status').textContent='已复制。';}catch{$('report-status').textContent='此浏览器未允许复制，请点“保存报告”。';}};
document.addEventListener('visibilitychange',()=>{if(document.hidden&&['talk','task','transition'].includes(phase))pause();});$('rest').addEventListener('cancel',e=>{e.preventDefault();resume();});
window.pilotInspect=()=>({version:PILOT_VERSION,subject:ep?.id,index,phase,paused,locked,step,task:task&&{id:task.id,kind:task.kind,goal:task.goal},audio:{id:cue?.file,who:cue?.who,voice:cue?.voice,intro:cue?.introDuration,time:audio.currentTime,duration:audio.duration,paused:audio.paused},positions:world?.positions(),speaker:world?.speaker,level:world?.level,mouths:world&&Object.fromEntries([...world.actors].map(([k,a])=>[k,Math.max(0,...a.morphs.map(m=>m.morphTargetInfluences[m.morphTargetDictionary.speak]||0))])),events:ep&&save[ep.id].events,report:makeReport()});window.cinemaReady=true;
if(navigator.serviceWorker?.controller)navigator.serviceWorker.getRegistration().then(r=>r?.update()).catch(()=>{});
