import * as T from 'three';
import {GLTFLoader} from './vendor/loaders/GLTFLoader.js';
import {mergeGeometries} from './vendor/utils/BufferGeometryUtils.js';

// The child is the camera. All selectable objects live in the rendered world.
export class SpringWorld {
  constructor(host,onPick,onDrag) {
    this.host=host;this.onPick=onPick;this.onDrag=onDrag;this.scene=new T.Scene();this.scene.background=new T.Color('#c8e6e1');this.scene.fog=new T.Fog('#c8e6e1',16,55);
    this.camera=new T.PerspectiveCamera(43,1,.05,90);this.renderer=new T.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});
    this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1;
    this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;host.append(this.renderer.domElement);
    this.scene.add(new T.HemisphereLight('#e4f5ff','#8a9162',1.8));const sun=new T.DirectionalLight('#fff1d4',2.2);sun.position.set(-7,12,7);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-12,right:12,top:12,bottom:-12,near:.1,far:35});sun.shadow.bias=-.0007;this.scene.add(sun);
    this.scene.add(new T.AmbientLight('#e8eee5',.2));this.ray=new T.Raycaster();this.mouse=new T.Vector2();this.objects=new Map();this.actors=[];this.floaters=[];this.tweens=[];this.disposed=[];this.time=0;this.paused=false;this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;this.view=new T.Vector3();this.look=new T.Vector3(0,1.2,0);this.camera.position.set(0,1.6,4.5);this.view.copy(this.camera.position);this.turn=0;this.seed=71;this.setupInputs();this.resize();new ResizeObserver(()=>this.resize()).observe(host);
    this.clock=new T.Clock();this.renderLoop=this.renderLoop.bind(this);requestAnimationFrame(this.renderLoop);
  }
  rand(){this.seed=(this.seed*1664525+1013904223)>>>0;return this.seed/4294967296;}
  mat(color,roughness=.82){return new T.MeshStandardMaterial({color,roughness});}
  mesh(geo,mat,parent=this.root){const m=new T.Mesh(geo,mat);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
  box(x,y,z,w,h,d,color,parent=this.root){const m=this.mesh(new T.BoxGeometry(w,h,d),this.mat(color),parent);m.position.set(x,y,z);return m;}
  ellipsoid(x,y,z,sx,sy,sz,color,parent=this.root){const m=this.mesh(new T.SphereGeometry(1,14,10),this.mat(color),parent);m.position.set(x,y,z);m.scale.set(sx,sy,sz);return m;}
  tube(points,r,color,parent=this.root){const curve=new T.CatmullRomCurve3(points.map(p=>new T.Vector3(...p)));return this.mesh(new T.TubeGeometry(curve,12,r,6,false),this.mat(color),parent);}
  texture(kind){const canvas=document.createElement('canvas');canvas.width=canvas.height=512;const c=canvas.getContext('2d'),im=c.createImageData(512,512);for(let y=0;y<512;y++)for(let x=0;x<512;x++){const v=kind==='hair'?128+38*Math.sin(x*1.3+Math.sin(y*.014)*7):128+28*Math.sin(x*1.9)*Math.sin(y*1.9);const i=(y*512+x)*4;im.data[i]=im.data[i+1]=im.data[i+2]=v;im.data[i+3]=255;}c.putImageData(im,0,0);const tex=new T.CanvasTexture(canvas);tex.wrapS=tex.wrapT=T.RepeatWrapping;tex.repeat.set(kind==='hair'?2:6,kind==='hair'?1:6);return tex;}
  async load(progress){const cloth=this.texture('cloth'),hair=this.texture('hair');this.template=(await new GLTFLoader().loadAsync('./assets/spring/spring.glb',e=>progress(e.total?e.loaded/e.total:0))).scene;this.template.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;for(const m of [].concat(o.material)){if(/hair/i.test(m.name)){m.roughness=.87;m.color.set('#24333c');m.bumpMap=hair;m.bumpScale=.003;}if(/jacket|scarf|pants|pullover/.test(m.name)){m.bumpMap=cloth;m.bumpScale=.006;}if(m.name.includes('jacket'))m.color.set('#c6aeb0');if(m.name==='Game_MAT_spring.head')m.roughness=.82;}}});this.enter('home');}
  clear(){if(this.root){this.scene.remove(this.root);this.root.traverse(o=>{if(o.userData.shared)return;if(o.geometry)o.geometry.dispose();if(o.material)[].concat(o.material).forEach(m=>{if(!m.userData.shared){m.map?.dispose();m.dispose();}});});}this.root=new T.Group();this.scene.add(this.root);this.objects.clear();this.actors=[];this.floaters=[];this.tweens=[];this.turn=0;this.seed=71;}
  enter(kind){this.kind=kind;this.clear();this.base(kind);if(kind==='home'||kind==='search'){this.actor('spring',.28,0,0);this.bench(-1.75,0,-1.9);this.tree(2.7,-1.6,1.1);this.planter(1.3,0,-1.6);this.paper('boat',-1.0,.72,-1.45,.4);this.paper('ribbon',1.5,.28,-1.6,.18);this.paper('leaf',.0,.14,1.1,.15);this.cameraTo([0,1.55,3.85],[.15,1.15,0],0);}
    if(kind==='hops'){this.stream();this.actor('spring',1.25,0,-3.4,.93);this.hopTargets=[];['circle','triangle','circle','triangle'].forEach((shape,i)=>{const x=i%2?.48:-.48,z=-.2-i*1.03;const m=this.stone(shape,x,.07,z,i);this.hopTargets.push(m);});this.cameraTo([0,1.6,2.1],[0,.3,-1],0);}
    if(kind==='team'){this.root.children.filter(o=>o.userData.ground).forEach(o=>o.material.color.set('#bac991'));this.stream();this.tree(-2,-2.5,1.1,true);this.tree(2.5,-3,.95,true);this.box(0,.11,-.65,1.9,.2,1.7,'#c3ad7e');this.actor('friend-0',-.62,.22,-.2,.9,'#b8998c');this.actor('friend-1',0,.22,-1.1,.93,'#75ada4');this.actor('friend-2',.62,.22,-.2,.9,'#a1a7ce');this.boat(0,.16,1.1);this.cameraTo([0,1.55,5.0],[0,.96,0],0);}
    if(kind==='welcome'){this.pavilion(0,-3.9);this.actor('spring',.35,0,-.35);this.lantern('lantern-self',-.45,1.0,.5,'#f8c770');this.cameraTo([0,1.6,4.1],[.05,1.15,0],0);}
    if(kind==='gather'){this.pavilion(0,-3.9);this.actor('friend-0',-.53,0,-.75,1);this.actor('friend-1',.53,0,-.75,1,'#80b1a2');this.lantern('lantern-left',-.55,.92,.15,'#eab79e');this.lantern('lantern-right',.55,.92,.15,'#d8bc79');this.cameraTo([0,1.6,4.7],[0,1.2,-.3],0);}
    if(kind==='festival'){this.pavilion(0,-3.9);this.actor('friend-0',-.55,0,-1.2);this.actor('friend-1',.55,0,-1.2,1,'#80b1a2');this.lantern('sky-lantern',0,1.1,.5,'#f2bc57');for(let i=0;i<8;i++){const a=i/8*Math.PI*2;this.lantern('light-'+i,Math.sin(a)*3,2.4+this.rand(),Math.cos(a)*3-2,'#edbb6a');}this.cameraTo([0,1.55,4.2],[0,1.3,-.3],0);}
    this.dragonfly=this.makeDragonfly();this.root.add(this.dragonfly);this.dragonfly.position.set(-.8,1.8,.5);this.batchScenery();
  }
  batchScenery(){this.root.updateMatrixWorld(true);const moving=new Set([...this.objects.values(),...this.floaters.map(f=>f.obj),this.dragonfly]);const buckets=new Map();this.root.traverse(o=>{if(!o.isMesh||o.isInstancedMesh||o.userData.shared||Array.isArray(o.material))return;let a=o;while(a&&a!==this.root){if(moving.has(a))return;a=a.parent;}const m=o.material,key=[m.type,m.color?.getHex(),m.roughness,m.opacity,m.side,m.shininess].join('/');if(!buckets.has(key))buckets.set(key,[]);buckets.get(key).push(o);});for(const list of buckets.values()){if(list.length<2)continue;const geos=list.map(o=>o.geometry.clone().applyMatrix4(o.matrixWorld));const merged=mergeGeometries(geos);geos.forEach(g=>g.dispose());if(!merged)continue;const mesh=new T.Mesh(merged,list[0].material.clone());mesh.castShadow=true;mesh.receiveShadow=true;this.root.add(mesh);for(const o of list){o.removeFromParent();o.geometry.dispose();o.material.dispose();}}}
  base(kind){const ground=this.mesh(new T.CircleGeometry(28,64),this.mat('#a7bf86'));ground.rotation.x=-Math.PI/2;ground.position.y=-.035;ground.userData.ground=true;
    // Curved garden path, individual paving stones, layered greenery.
    const path=this.mesh(new T.PlaneGeometry(3.5,17),this.mat('#e9dbb4'));path.rotation.x=-Math.PI/2;path.position.set(0,-.014,-3);
    for(let z=2;z>-9;z-=.58)for(let s=-1;s<=1;s++){const p=this.box(s*.85+(this.rand()-.5)*.18,.012,z,.75,.035,.5,'#ddd4b3');p.rotation.y=(this.rand()-.5)*.15;}
    for(let i=0;i<9;i++){const side=i%2?1:-1;this.tree(side*(3.2+this.rand()*4),-3-i*1.3,.85+this.rand()*.6,kind==='festival'||kind==='team');}
    this.grass();for(let i=0;i<12;i++){let x=(this.rand()-.5)*12,z=-1-this.rand()*10;if(Math.abs(x)<2)x+=Math.sign(x||1)*2;this.flowers(x,z);}
    for(let i=0;i<6;i++){const m=this.ellipsoid(-19+i*8,2,-30-this.rand()*6,7,4+this.rand()*5,4,['#85b4ae','#91c2b5','#a2cec5'][i%3]);m.castShadow=false;}
    for(let i=0;i<6;i++){const c=this.ellipsoid(-13+i*6,10+this.rand()*3,-22,3,1,1.5,'#eef5df');c.castShadow=false;}
    this.pond(-4.5,-1.4,2.5);this.pond(4.4,-1.9,2.3);
    for(let i=0;i<12;i++){const x=(i%2?1:-1)*(2.7+this.rand()*2),z=-this.rand()*4;this.lotus(x,z,.2+this.rand()*.12);}
    const dustGeo=new T.BufferGeometry();let points=[];for(let i=0;i<55;i++)points.push((this.rand()-.5)*10,this.rand()*4,-this.rand()*8);dustGeo.setAttribute('position',new T.Float32BufferAttribute(points,3));this.dust=new T.Points(dustGeo,new T.PointsMaterial({color:'#ffffd4',size:.026,transparent:true,opacity:.65}));this.root.add(this.dust);
  }
  tree(x,z,scale=1,pink=false){const g=new T.Group();g.position.set(x,0,z);g.scale.setScalar(scale);this.root.add(g);this.tube([[0,0,0],[.13,1,0],[-.09,2.2,.05],[.2,3.5,0]],.13,'#746849',g);for(let k=0;k<5;k++){const a=k*2.4;const px=Math.cos(a),pz=Math.sin(a)*.8;this.tube([[0,1.65,0],[px*.45,2.5,pz*.5],[px,3.1,pz]],.05,'#817654',g);}
    const geo=new T.SphereGeometry(1,10,7);const leaves=new T.InstancedMesh(geo,this.mat(pink?'#e5b6b0':'#8cac69'),110);leaves.castShadow=true;g.add(leaves);const d=new T.Object3D();for(let i=0;i<110;i++){const a=this.rand()*6.28,r=Math.sqrt(this.rand())*1.6;d.position.set(Math.cos(a)*r,2.8+this.rand()*1.3-r*.22,Math.sin(a)*r*.85);d.scale.set(.22+this.rand()*.26,.1+this.rand()*.16,.25+this.rand()*.24);d.rotation.set(this.rand(),a,this.rand());d.updateMatrix();leaves.setMatrixAt(i,d.matrix);leaves.setColorAt(i,new T.Color(pink?'#edc4b7':'#a9c885').multiplyScalar(.72+this.rand()*.5));}leaves.instanceMatrix.needsUpdate=true;
  }
  grass(){const g=new T.ConeGeometry(.035,.28,3);const m=new T.InstancedMesh(g,this.mat('#799451'),380);const d=new T.Object3D();for(let i=0;i<380;i++){let x=(this.rand()-.5)*18,z=(this.rand()-.5)*18-4;if(Math.abs(x)<1.9)x+=Math.sign(x||1)*2;d.position.set(x,.1,z);d.rotation.set((this.rand()-.5)*.4,this.rand()*6.28,(this.rand()-.5)*.4);d.scale.setScalar(.5+this.rand());d.updateMatrix();m.setMatrixAt(i,d.matrix);}this.root.add(m);}
  flowers(x,z){const g=new T.Group();g.position.set(x,0,z);this.root.add(g);for(let i=0;i<4;i++){const px=(this.rand()-.5)*.65,pz=(this.rand()-.5)*.65,h=.23+this.rand()*.35;this.tube([[px,0,pz],[px+.035,h,pz]],.013,'#668952',g);this.ellipsoid(px,h,pz,.055,.055,.055,'#f2c85c',g);for(let j=0;j<5;j++){const a=j*1.256;this.ellipsoid(px+Math.cos(a)*.072,h,pz+Math.sin(a)*.072,.065,.03,.065,i%2?'#f5ecdb':'#eac1c6',g);}}}
  pond(x,z,r){const water=this.mesh(new T.CircleGeometry(r,56),new T.MeshPhongMaterial({color:'#68b4b0',shininess:80,transparent:true,opacity:.9}));water.rotation.x=-Math.PI/2;water.position.set(x,-.004,z);for(let i=0;i<8;i++){const ring=this.mesh(new T.RingGeometry(.2+i*.2,.208+i*.2,40),new T.MeshBasicMaterial({color:'#d0f4d9',transparent:true,opacity:.22,side:T.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.set(x,.003,z);this.floaters.push({obj:ring,base:.003,phase:i,water:true});}}
  lotus(x,z,s){const shape=new T.Shape();shape.moveTo(0,0);for(let i=1;i<=30;i++){const a=.15+i/30*5.94;shape.lineTo(Math.sin(a)*s,Math.cos(a)*s);}shape.lineTo(0,0);const leaf=this.mesh(new T.ShapeGeometry(shape),new T.MeshStandardMaterial({color:'#6d9c6a',roughness:.7,side:T.DoubleSide}));leaf.rotation.x=-Math.PI/2;leaf.position.set(x,.04,z);if(this.rand()>.45){for(let i=0;i<7;i++){let a=i*.9;const p=this.ellipsoid(x+Math.cos(a)*s*.27,.14,z+Math.sin(a)*s*.27,s*.18,s*.32,s*.14,'#e5adbf');p.rotation.z=Math.cos(a)*.55;}}}
  bench(x,y,z){const g=new T.Group();g.position.set(x,y,z);g.rotation.y=.12;this.root.add(g);for(let i=0;i<3;i++)this.box(0,.48,i*.13,1.55,.075,.11,'#af9169',g);for(let i=0;i<2;i++)this.box(0,.73+i*.14,-.15,1.55,.1,.07,'#baa279',g);for(const s of [-1,1]){this.box(s*.6,.25,.05,.085,.5,.36,'#65796b',g);this.box(s*.6,.66,-.14,.07,.6,.07,'#65796b',g);}}
  planter(x,y,z){this.box(x,y+.18,z,.9,.36,.8,'#d6b78e');this.box(x,y+.37,z,.94,.05,.84,'#ddc7a3');for(let i=0;i<3;i++)this.flowers(x+(i-1)*.18,z);}
  pavilion(x,z){const g=new T.Group();g.position.set(x,0,z);this.root.add(g);this.box(0,.09,0,3.7,.18,2.8,'#bdc5b1',g);for(const a of [-1,1])for(const b of [-1,1])this.box(a*1.45,1.3,b, .1,2.5,.1,'#a47a53',g);const roof=this.mesh(new T.ConeGeometry(2.75,1.15,4),this.mat('#648b83'),g);roof.rotation.y=Math.PI/4;roof.scale.z=.83;roof.position.y=2.75;const lip=this.mesh(new T.ConeGeometry(2.94,.25,4,1,true),this.mat('#8dafa0'),g);lip.rotation.y=Math.PI/4;lip.scale.z=.83;lip.position.y=2.22;this.box(0,2.15,0,3.3,.12,2.5,'#a68d61',g);}
  actor(id,x,y,z,scale=1,tint){const a=this.template.clone(true);a.scale.setScalar(1.27*scale);a.position.set(x,y,z);a.traverse(o=>{o.userData.shared=true;if(o.isMesh){if(tint&&o.material.name?.includes('jacket')){o.material=o.material.clone();o.material.color.set(tint);}}});a.userData.base=y;this.root.add(a);this.actors.push(a);this.objects.set(id,a);a.userData.id=id;a.userData.head=a.getObjectByName('Spring_head_pivot');return a;}
  paper(id,x,y,z,s){const g=new T.Group();g.position.set(x,y,z);const shape=new T.Shape();shape.moveTo(-1,0);shape.lineTo(0,.7);shape.lineTo(1,0);shape.lineTo(.6,-.3);shape.lineTo(-.6,-.3);shape.closePath();const m=this.mesh(new T.ExtrudeGeometry(shape,{depth:.04,bevelEnabled:false}),this.mat('#fff0c6'),g);m.rotation.x=-.55;g.scale.setScalar(s);const hit=new T.Mesh(new T.SphereGeometry(1.2,8,6),new T.MeshBasicMaterial({transparent:true,opacity:0,depthWrite:false}));g.add(hit);this.root.add(g);g.userData.id=id;this.objects.set(id,g);return g;}
  boat(x,y,z){const g=new T.Group();g.position.set(x,y,z);this.root.add(g);const hull=this.mesh(new T.SphereGeometry(1,16,8,0,Math.PI*2,0,Math.PI/2),new T.MeshStandardMaterial({color:'#c5a06c',side:T.DoubleSide,roughness:.9}),g);hull.rotation.z=Math.PI;hull.scale.set(.7,.2,1.0);this.box(0,0,0,1.1,.05,1.5,'#d0b488',g);for(const s of [-1,1])this.box(s*.64,.16,0,.08,.22,1.65,'#a58056',g);this.objects.set('big-boat',g);g.userData.id='big-boat';}
  stream(){const river=this.mesh(new T.PlaneGeometry(4.4,5.6),new T.MeshPhongMaterial({color:'#6bbbbe',shininess:90}));river.rotation.x=-Math.PI/2;river.position.set(0,.04,-1.2);for(let i=0;i<22;i++){const m=this.mesh(new T.PlaneGeometry(.16+this.rand()*.5,.018),new T.MeshBasicMaterial({color:'#c9ede0',transparent:true,opacity:.5}));m.rotation.x=-Math.PI/2;m.position.set((this.rand()-.5)*4,.045,-3.7+this.rand()*5);this.floaters.push({obj:m,base:m.position.x,phase:i,stream:true});}}
  stone(shape,x,y,z,i){const g=new T.Group();g.position.set(x,y,z);this.root.add(g);let m;if(shape==='circle'){m=this.mesh(new T.CylinderGeometry(.42,.44,.14,40),this.mat('#cfdab1'),g);const ring=this.mesh(new T.TorusGeometry(.31,.018,6,36),this.mat('#f6efc7'),g);ring.rotation.x=Math.PI/2;ring.position.y=.08;}else{m=this.mesh(new T.CylinderGeometry(.51,.53,.14,3),this.mat('#d9c6a2'),g);m.rotation.y=Math.PI;const geo=new T.BufferGeometry().setFromPoints([new T.Vector3(0,.08,-.37),new T.Vector3(.32,.08,.19),new T.Vector3(-.32,.08,.19),new T.Vector3(0,.08,-.37)]);g.add(new T.Line(geo,new T.LineBasicMaterial({color:'#fff0cc'})));}g.userData.id='stone-'+i;g.userData.shape=shape;this.objects.set(g.userData.id,g);return g;}
  lantern(id,x,y,z,color){const g=new T.Group();g.position.set(x,y,z);this.root.add(g);const body=this.mesh(new T.SphereGeometry(.22,16,12),new T.MeshStandardMaterial({color,roughness:.72,emissive:color,emissiveIntensity:.05}),g);body.scale.set(1,1.18,1);for(const s of [-1,1]){const c=this.mesh(new T.CylinderGeometry(.115,.115,.04,16),this.mat('#af8050'),g);c.position.y=s*.245;}this.tube([[0,.25,0],[0,.58,0]],.01,'#9a7b53',g);this.tube([[0,-.26,0],[0,-.43,0]],.012,'#c3944f',g);g.userData.id=id;g.userData.body=body;this.objects.set(id,g);this.floaters.push({obj:g,base:y,phase:this.floaters.length});return g;}
  makeDragonfly(){const g=new T.Group();this.ellipsoid(0,0,0,.055,.055,.08,'#759455',g);this.ellipsoid(0,0,.15,.027,.027,.15,'#6c955c',g);for(const s of [-1,1]){this.ellipsoid(s*.027,.025,-.06,.025,.028,.022,'#d7d9a2',g);this.ellipsoid(s*.03,.032,-.079,.01,.013,.01,'#283f30',g);for(const z of [0,.07]){const w=this.mesh(new T.SphereGeometry(1,12,6),new T.MeshPhongMaterial({color:'#b4e4df',transparent:true,opacity:.65,shininess:75}),g);w.scale.set(.15,.005,.045);w.position.set(s*.14,.02,z);w.rotation.y=s*.3;w.userData.wing=s;}}return g;}
  cameraTo(pos,target,duration=1.1,jump=false){const start=this.view.clone(),end=new T.Vector3(...pos),lookStart=this.look.clone(),lookEnd=new T.Vector3(...target);this.turn=0;if(duration===0||this.reduced){this.view.copy(end);this.look.copy(lookEnd);return Promise.resolve();}return new Promise(resolve=>this.tweens.push({t:0,d:duration,fn:k=>{const e=k*k*(3-2*k);this.view.lerpVectors(start,end,e);this.look.lerpVectors(lookStart,lookEnd,e);if(jump)this.view.y+=Math.sin(k*Math.PI)*.25;},end:resolve}));}
  tween(fn,d=.8){if(this.reduced){fn(1);return Promise.resolve();}return new Promise(resolve=>this.tweens.push({t:0,d,fn,end:resolve}));}
  async collect(id){const o=this.objects.get(id);if(!o)return;const p=o.position.clone(),end=this.view.clone().add(new T.Vector3(.2,-.45,-.7));await this.tween(k=>{o.position.lerpVectors(p,end,k);o.rotation.y=k*2;o.scale.multiplyScalar(1);},.5);o.visible=false;}
  async light(id){const o=this.objects.get(id);if(!o)return;await this.tween(k=>{o.userData.body.material.emissiveIntensity=.1+k*1.2;},.5);}
  async invite(id,slot){const o=this.objects.get(id),b=this.objects.get('big-boat');if(!o||!b)return;const p=o.position.clone(),end=new T.Vector3(slot?.36:-.36,.21,1.08);o.userData.selected=true;await this.tween(k=>{o.position.lerpVectors(p,end,k);o.position.y+=Math.abs(Math.sin(k*Math.PI*4))*.045;},.9);b.attach(o);}
  async launch(){const b=this.objects.get('big-boat')||this.objects.get('sky-lantern');if(!b)return;const p=b.position.clone(),v=this.view.clone(),l=this.look.clone();await this.tween(k=>{b.position.y=p.y+k*(this.kind==='festival'?3:.05);b.position.z=p.z-k*5;if(this.kind==='team'){this.view.z=v.z-k*2.8;this.look.z=l.z-k*3.5;}},2);}
  objectScreen(id){const o=this.objects.get(id);if(!o||!o.visible)return null;const p=new T.Vector3();o.getWorldPosition(p);if(id.startsWith('friend')||id==='spring')p.y+=1.15;p.project(this.camera);const r=this.host.getBoundingClientRect();return {x:(p.x*.5+.5)*r.width,y:(-p.y*.5+.5)*r.height,visible:p.z<1&&Math.abs(p.x)<1&&Math.abs(p.y)<1};}
  setupInputs(){let start=null;const c=this.renderer.domElement;c.addEventListener('pointerdown',e=>{if(this.paused)return;start={x:e.clientX,y:e.clientY,turn:this.turn};c.setPointerCapture(e.pointerId);});c.addEventListener('pointermove',e=>{if(!start||this.paused)return;const dx=e.clientX-start.x;if(Math.abs(dx)>12)this.turn=T.MathUtils.clamp(start.turn-dx/600,-.28,.28);});c.addEventListener('pointerup',e=>{if(!start||this.paused){start=null;return;}const dx=e.clientX-start.x,dy=e.clientY-start.y;start=null;if(Math.abs(dy)>55&&Math.abs(dy)>Math.abs(dx)){this.onDrag?.(dy);return;}if(Math.abs(dx)>18||Math.abs(dy)>18)return;const rect=c.getBoundingClientRect();this.mouse.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);this.ray.setFromCamera(this.mouse,this.camera);const hits=this.ray.intersectObjects([...this.objects.values()].filter(o=>o.visible),true);let picked=null;for(const h of hits){let o=h.object;while(o&&!o.userData.id)o=o.parent;if(o){picked=o.userData.id;break;}}this.onPick?.(picked,{x:e.clientX-rect.left,y:e.clientY-rect.top});});c.addEventListener('pointercancel',()=>start=null);}
  resize(){const r=this.host.getBoundingClientRect();this.renderer.setSize(r.width,r.height);this.camera.aspect=r.width/r.height;this.camera.fov=r.width>r.height?50:43;this.camera.updateProjectionMatrix();}
  renderLoop(){requestAnimationFrame(this.renderLoop);const dt=Math.min(this.clock.getDelta(),.045);if(!this.paused){this.time+=dt;for(let i=this.tweens.length-1;i>=0;i--){const a=this.tweens[i];a.t+=dt;const k=Math.min(a.t/a.d,1);a.fn(k);if(k===1){this.tweens.splice(i,1);a.end?.();}}for(let i=0;i<this.actors.length;i++){const a=this.actors[i];const h=a.userData.head;if(h){h.rotation.y=Math.sin(this.time*.8+i)*.045;h.rotation.x=Math.sin(this.time*1.2+i)*.018;}if(!this.reduced)a.scale.y=1.27*(a.scale.x/1.27)*(1+Math.sin(this.time*1.6+i)*.0025);}for(const f of this.floaters){if(this.reduced)continue;if(f.stream)f.obj.position.x=f.base+Math.sin(this.time*.35+f.phase)*.2;else if(f.water)f.obj.scale.setScalar(1+Math.sin(this.time*.5+f.phase)*.08);else if(!f.obj.userData.released)f.obj.position.y=f.base+Math.sin(this.time+f.phase)*.025;}if(this.dragonfly&&!this.reduced){this.dragonfly.position.set(-.85+Math.sin(this.time*.55)*.23,1.7+Math.sin(this.time*1.7)*.06,.6+Math.cos(this.time*.55)*.12);this.dragonfly.children.forEach(o=>{if(o.userData.wing)o.rotation.z=Math.sin(this.time*40)*.28*o.userData.wing;});}if(this.dust&&!this.reduced)this.dust.rotation.y=this.time*.006;}
    this.camera.position.copy(this.view);const target=this.look.clone();target.x+=Math.sin(this.turn)*3;this.camera.lookAt(target);this.renderer.render(this.scene,this.camera);this.afterRender?.();
  }
}
