import {SpringWorld} from './spring-world.js?v=20260916c';
const $=s=>document.querySelector(s),show=(s,yes=true)=>$(s).hidden=!yes;
const KEY='luoyi-spring-story-v1',VERSION='20260916c';
const empty=()=>({step:0,done:false,seconds:0,actions:0,retries:0,hints:0,listens:0,found:[],invited:[],lit:[],observation:'',oral:'暂未观察',updated:''});
let data={schema:1,math:empty(),chinese:empty()},storageOK=true;
try{const raw=localStorage.getItem(KEY);if(raw)data=validate(JSON.parse(raw));}catch{storageOK=false;}
function validate(d){if(!d||d.schema!==1)throw Error('进度格式不正确');const result={schema:1};for(const s of ['math','chinese']){const o=d[s];if(!o||typeof o!=='object')throw Error('缺少两科进度');const r=empty();for(const k of ['step','seconds','actions','retries','hints','listens'])if(Number.isFinite(o[k])&&o[k]>=0)r[k]=Math.min(Math.floor(o[k]),k==='step'?30:100000);r.done=o.done===true;for(const k of ['found','invited','lit'])if(Array.isArray(o[k]))r[k]=o[k].filter(v=>typeof v==='string'&&v.length<30).slice(0,6);r.observation=typeof o.observation==='string'?o.observation.slice(0,500):'';r.oral=['自己读了一句','跟读了一句'].includes(o.oral)?o.oral:'暂未观察';r.updated=typeof o.updated==='string'?o.updated.slice(0,32):'';result[s]=r;}return result;}
function save(){try{localStorage.setItem(KEY,JSON.stringify(data));storageOK=true;}catch{storageOK=false;}}
const phrases=[['我是中国人。','wǒ shì zhōng guó rén'],['我们都是中国人。','wǒ men dōu shì zhōng guó rén'],['中华民族是一家。','zhōng huá mín zú shì yì jiā']];
function ruby(text,py){const chars=[...text],tones=py.split(' ');let i=0;return chars.map(c=>/[\u3400-\u9fff]/.test(c)?`<ruby>${c}<rt>${tones[i++]||''}</rt></ruby>`:c).join('');}
function knowledge(n){show('#knowledge',n!==null);if(n!==null)$('#knowledge').innerHTML=ruby(...phrases[n]);}
let subject=null,step=0,busy=false,muted=false,reportSubject='math',restElapsed=0,active=true,lastSave=0,started=performance.now(),hintedAt=0;
let world,currentLine='',target=null,selected=[],lit=[],sceneKind='',actionTime=0;
const math=[
  {scene:'search',title:'风把纸船吹走了',line:'珞伊，纸船的帆散在花园里了。和我一起找回来，好吗？',button:'去找纸船'},
  {scene:'search',title:'花园寻踪 · 长凳',line:'先找长凳旁边。纸船露出了一个小尖角。',target:'boat',hint:'滑一滑看看四周，再点一点击长凳边的纸船。'},
  {scene:'search',title:'花园寻踪 · 花坛',line:'找到了！另一片船帆落在花坛里，花朵把它藏住了。',target:'ribbon',hint:'看看右边花坛里浅金色的纸片。'},
  {scene:'search',title:'花园寻踪 · 小路',line:'最后一片就在小路上。我们从长凳、花坛找到了小路！',target:'leaf',hint:'看看前面脚边的小纸片。'},
  {scene:'hops',title:'溪流上的秘密',line:'纸船修好了！小溪挡住了路：圆圈用双脚，三角形用单脚。',button:'来到溪边'},
  ...['circle','triangle','circle','triangle'].map((shape,i)=>({scene:'hops',title:`踏石过溪 · ${i+1}/4`,line:i===0?'看前面第一块踏石，准备跳过去。':i===3?'最后一块！留意形状有没有变。':'落稳啦，看看下一块踏石。',shape,target:'stone-'+i})),
  {scene:'team',title:'桃花下的小船',line:'伙伴们都来了！小船要坐三个人。珞伊也在船上，还要邀请几位伙伴？',button:'去邀请伙伴'},
  {scene:'team',title:'桃花朵朵开 · 开3朵',line:'点点伙伴，请她上船。想换一位，就再点她一次。',team:true},
  {scene:'team',title:'纸船出发啦',line:'珞伊和两位伙伴，合起来三个人。一起把纸船送进小溪吧！',button:'让纸船出发'}
];
const chinese=[
  {scene:'welcome',title:'谁来点亮第一盏灯',line:'珞伊，欢迎会还少一盏灯。你愿意来点亮自己的小灯笼吗？',button:'走近小灯笼'},
  {scene:'welcome',title:'属于珞伊的灯',line:'点一点面前的小灯笼。第一盏灯，欢迎你来到这里。',target:'lantern-self'},
  {scene:'welcome',title:'认识自己',line:'我是中国人。珞伊，你想说的时候，也可以说给我听。',phrase:0,button:'带着灯去找朋友'},
  {scene:'gather',title:'两边都亮起来',line:'朋友们的灯还没亮。把左边、右边的小灯笼都点亮，让大家看见彼此。',light:true},
  {scene:'gather',title:'从我到我们',line:'我们都是中国人。小灯相聚，大家就坐到了一起。',phrase:1,button:'一起去欢迎会'},
  {scene:'festival',title:'把祝福送上天空',line:'一盏盏灯，带来不同地方朋友的祝福。向上轻轻一推，送出珞伊的灯。',release:true},
  {scene:'festival',title:'相聚的一家人',line:'中华民族是一家。珞伊，谢谢你点亮了今天的欢迎会。',phrase:2,button:'收好今天的故事'}
];
function actions(items){const el=$('#actions');el.replaceChildren();for(const a of items){const b=document.createElement('button');b.textContent=a.text;if(a.secondary)b.className='secondary';if(a.id)b.id=a.id;b.onclick=async()=>{if(busy)return;await a.run();};el.append(b);}}
function say(text){currentLine=text;$('#line').textContent=text;if(muted||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='zh-CN';u.rate=.86;u.pitch=1.12;const voice=speechSynthesis.getVoices().find(v=>/^zh[-_]CN/i.test(v.lang));if(voice)u.voice=voice;speechSynthesis.speak(u);}
function chime(good=true){if(muted)return;try{const A=window.AudioContext||window.webkitAudioContext;const ctx=chime.ctx||(chime.ctx=new A());ctx.resume();const t=ctx.currentTime;[0,.1,.22].forEach((d,i)=>{const o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.value=(good?[523,659,784]:[440,392,440])[i];g.gain.setValueAtTime(.0001,t+d);g.gain.exponentialRampToValueAtTime(.05,t+d+.018);g.gain.exponentialRampToValueAtTime(.0001,t+d+.25);o.connect(g).connect(ctx.destination);o.start(t+d);o.stop(t+d+.27);});}catch{}}
function tickRecord(type){if(!subject)return;data[subject][type]++;data[subject].updated=new Date().toISOString();save();}
function home(){speechSynthesis?.cancel();subject=null;busy=false;target=null;sceneKind='home';world.paused=false;world.enter('home');show('#home');show('#play',false);show('#chapter',false);show('#target-mark',false);$('#title').textContent='珞伊的蜻蜓秘境';$('#lesson').textContent='选择今天的故事';for(const s of ['math','chinese'])$('#'+s+'-saved').textContent=data[s].done?'故事已收好 · 可以重玩':data[s].step?'继续上次的冒险':'';}
function start(s){subject=s;step=data[s].done?0:Math.min(data[s].step,(s==='math'?math:chinese).length-1);if(data[s].done){data[s]=empty();save();}restElapsed=0;sceneKind='';show('#home',false);show('#play');show('#chapter');$('#title').textContent=s==='math'?'珞伊的数学探险':'珞伊的语文故事';renderStep();}
async function renderStep(){const stages=subject==='math'?math:chinese,s=stages[step];if(!s)return;data[subject].step=step;save();busy=false;target=s.target||null;actionTime=world.time;hintedAt=0;$('#hint').textContent='';$('#chapter-name').textContent=s.title;$('#progress').textContent=subject==='math'?(step<4?'1 / 3':step<9?'2 / 3':'3 / 3'):(step<3?'1 / 3':step<5?'2 / 3':'3 / 3');$('#lesson').textContent=subject==='chinese'?'语文｜我上学了·我是中国人｜第2页':step<4?'数学｜数学游戏·在校园里找一找':step<9?'数学｜数学游戏·单脚跳、双脚跳':'数学｜数学游戏·桃花朵朵开（开3朵）';
  if(sceneKind!==s.scene){sceneKind=s.scene;world.enter(s.scene);}knowledge(s.phrase??null);say(s.line);$('#gesture').textContent=s.release?'向上轻推灯笼':s.shape?'看清踏石，再选择跳法':s.team?'点伙伴邀请，再点可取消':'点场景里的物品 · 左右滑动环顾';
  if(subject==='math'&&step===4){show('#knowledge');$('#knowledge').innerHTML=`${ruby('圆圈','yuán quān')} → ${ruby('双脚','shuāng jiǎo')}<br>${ruby('三角形','sān jiǎo xíng')} → ${ruby('单脚','dān jiǎo')}`;}
  if(subject==='math'&&step>=1&&step<=3){for(let i=0;i<step-1;i++)world.objects.get(['boat','ribbon','leaf'][i]).visible=false;const poses=[null,[[0,1.42,3.5],[-.55,.9,-.2]],[[.25,1.42,2.5],[1.12,.75,-1.2]],[[0,1.45,2.9],[0,.30,.65]]];world.cameraTo(...poses[step],.75);}
  if(s.shape){const i=step-5;const p=i===0?[0,1.6,2.1]:[world.hopTargets[i-1].position.x,1.4,world.hopTargets[i-1].position.z+.36];world.cameraTo(p,[world.hopTargets[i].position.x,.07,world.hopTargets[i].position.z],.5);actions([{text:'单脚跳',id:'jump-single',run:()=>jump('triangle')},{text:'双脚跳',id:'jump-double',run:()=>jump('circle')}]);}
  else if(s.team){selected=[];actions([{text:'一起上船',id:'board',run:board}]);}
  else if(s.light){lit=[];actions([]);}
  else if(s.release){actions([{text:'向上送出灯笼',id:'release',run:release}]);}
  else if(s.button)actions([{text:s.button,id:'continue',run:async()=>{if(subject==='math'&&step===11){busy=true;await world.launch();complete();}else if(subject==='chinese'&&step===6)complete();else next();}}]);else actions([]);
}
function next(){step++;renderStep();}
async function pick(id,point){if(!subject||busy||world.paused)return;const s=(subject==='math'?math:chinese)[step];const glow=$('#touch-glow');glow.style.left=point.x+'px';glow.style.top=point.y+'px';glow.animate([{opacity:.8,scale:'.7'},{opacity:0,scale:'1.5'}],{duration:350});
  if(s.team&&id?.startsWith('friend-')){const idx=selected.indexOf(id),o=world.objects.get(id);if(idx>=0){selected.splice(idx,1);o.rotation.y=0;o.userData.selected=false;}else{selected.push(id);o.rotation.y=-.22;o.userData.selected=true;}tickRecord('actions');$('#hint').textContent=`珞伊 ＋ ${selected.length}位伙伴，船上共${selected.length+1}人。`;chime();return;}
  if(s.light&&['lantern-left','lantern-right'].includes(id)&&!lit.includes(id)){const originalStep=step;tickRecord('actions');lit.push(id);await world.light(id);chime();if(step===originalStep){if(lit.length===2){data.chinese.lit=lit.slice();next();}else say('这边亮了，另一边的朋友也在等我们。');}return;}
  if(!s.shape&&id&&id===target){busy=true;tickRecord('actions');target=null;if(subject==='math'){await world.collect(id);data.math.found.push(id);}else await world.light(id);chime();next();return;}
  if(s.target&&!s.shape){$('#hint').textContent=s.hint||'看看面前的小灯笼，轻轻点一点。';tickRecord('hints');hintedAt=world.time;}
}
async function jump(shape){const s=math[step];if(!s?.shape)return;tickRecord('actions');if(shape!==s.shape){tickRecord('retries');$('#hint').innerHTML=s.shape==='circle'?`${ruby('圆圈','yuán quān')}用双脚。看清这一块，再试试。`:`${ruby('三角形','sān jiǎo xíng')}用单脚。看清这一块，再试试。`;say(s.shape==='circle'?'这块是圆圈，让两只脚一起落稳。':'这块是三角形，试试用单脚落稳。');chime(false);return;}busy=true;const o=world.hopTargets[step-5];await world.cameraTo([o.position.x,1.4,o.position.z+.36],[o.position.x,.35,o.position.z-.8],.85,true);chime();next();}
async function board(){tickRecord('actions');if(selected.length!==2){tickRecord('retries');say(selected.length<2?'别忘了珞伊自己也在船上。再邀请伙伴一起凑成三个人吧。':'小船只能坐三个人，珞伊也占一个位置。点一位伙伴，让她在岸边等我们。');$('#hint').textContent=`现在共${selected.length+1}人（包括珞伊）。`;return;}busy=true;data.math.invited=selected.slice();await Promise.all(selected.map((id,i)=>world.invite(id,i)));chime();next();}
async function release(){if(busy||subject!=='chinese'||step!==5)return;busy=true;tickRecord('actions');const lamp=world.objects.get('sky-lantern');lamp.userData.released=true;await world.light('sky-lantern');await world.launch();chime();next();}
function complete(){data[subject].done=true;save();show('#oral-open',subject==='chinese');$('#finish-title').textContent=subject==='math'?'珞伊，纸船启航了！':'珞伊，欢迎灯亮了！';$('#finish-text').textContent=subject==='math'?'你找回了船帆，走过小溪，还邀请伙伴一起出发。下次在生活里，也试试把自己算进去。':'从自己的小灯，到大家的灯，欢迎会因你而亮起来。想说哪一句，就说给家人听。';openModal('#finish');}
function openModal(sel){world.paused=true;speechSynthesis?.cancel();$(sel).showModal();}
function closeModal(sel){$(sel).close();world.paused=!!document.querySelector('dialog[open]')||!active;}
function makeReport(s){const r=data[s];const date=r.updated?new Date(r.updated).toLocaleString('zh-CN'):'尚未开始';return `珞伊的${s==='math'?'数学探险':'语文故事'}过程记录\n版本：${VERSION}｜最后操作：${date}\n教材：${s==='math'?'数学游戏·校园观察、单/双脚跳、桃花朵朵开':'我上学了·我是中国人（第2页）'}\n状态：${r.done?'完成本次故事':r.actions?'进行中':'尚未开始'}\n有效活动时长：${Math.floor(r.seconds/60)}分${Math.floor(r.seconds%60)}秒\n场景操作：${r.actions}次；提示记录：${r.hints}次；重听：${r.listens}次\n${s==='math'?`跳法或组队需要再尝试：${r.retries}次\n找到物品：${new Set(r.found).size}/3；三人组队：${r.invited.length===2?'已完成':'尚未完成'}`:`点亮伙伴灯：${new Set(r.lit).size}/2\n朗读（家长观察）：${r.oral}`}\n家长补充：${r.observation||'暂未填写'}\n\n怎么看：这是设备记录的操作，不是考试。误触、帮助与理解差异需要家长区分；听读不等于独立识字，通关不代表已掌握。\n下次陪伴：${s==='math'?'在现实里找一处圆形或三角形，或与家人组成含自己的三人小队。任选一件，不加练习单。':'请珞伊自愿挑一句说给家人听；不愿说就先听，不用背诵或评分。'}\n\n此记录仅在本浏览器，未自动发送给老师或 Codex。`;}
function updateReport(){for(const s of ['math','chinese'])$('#report-'+s).classList.toggle('active',s===reportSubject);$('#report').textContent=makeReport(reportSubject);$('#observation').value=data[reportSubject].observation;$('#report-note').textContent=storageOK?'':'浏览器没有成功保存进度。请复制或导出记录后再离开。';}
function parents(){reportSubject=subject||'math';updateReport();openModal('#parents');}
$('#math').onclick=()=>start('math');$('#chinese').onclick=()=>start('chinese');$('#parent').onclick=parents;$('#pause').onclick=()=>{clearRecording();openModal('#rest');};$('#resume').onclick=()=>{restElapsed=0;closeModal('#rest');};$('#rest-home').onclick=()=>{closeModal('#rest');home();};$('#back').onclick=home;$('#finish-home').onclick=()=>{closeModal('#finish');home();};$('#finish-report').onclick=()=>{closeModal('#finish');parents();};$('#listen').onclick=()=>{tickRecord('listens');say(currentLine);};$('#sound').onclick=()=>{muted=!muted;$('#sound').textContent=muted?'声音关':'声音开';$('#sound').setAttribute('aria-label',muted?'打开声音':'关闭声音');if(muted)speechSynthesis?.cancel();else say(currentLine);};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{const d=b.closest('dialog');if(d.id==='oral')clearRecording();closeModal('#'+d.id);});document.querySelectorAll('dialog').forEach(d=>d.addEventListener('cancel',()=>{if(d.id==='oral')clearRecording();setTimeout(()=>world.paused=!!document.querySelector('dialog[open]')||!active,0);}));
for(const s of ['math','chinese'])$('#report-'+s).onclick=()=>{reportSubject=s;updateReport();};$('#observation').oninput=()=>{data[reportSubject].observation=$('#observation').value;save();$('#report').textContent=makeReport(reportSubject);};
$('#copy-report').onclick=async()=>{try{await navigator.clipboard.writeText(makeReport(reportSubject));$('#report-note').textContent='已复制。可粘贴给老师，或发到当前对话。';}catch{$('#report-note').textContent='本浏览器不允许自动复制。请长按报告文字复制，或点“保存报告”。';}};
$('#download-report').onclick=()=>{const a=document.createElement('a'),url=URL.createObjectURL(new Blob([makeReport(reportSubject)],{type:'text/plain;charset=utf-8'}));a.href=url;a.download=`珞伊-${reportSubject==='math'?'数学':'语文'}故事记录.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('#export').onclick=()=>{$('#transfer').value=JSON.stringify(data);$('#transfer-note').textContent='复制这段进度文字，在另一设备粘贴并导入即可。';};$('#import').onclick=()=>{try{const raw=$('#transfer').value;if(raw.length>100000)throw Error();const imported=validate(JSON.parse(raw));data=imported;save();$('#transfer-note').textContent='两科进度已导入，回到故事小屋后生效。';updateReport();}catch{$('#transfer-note').textContent='格式不正确，原进度未更改。请粘贴完整导出内容。';}};$('#motion').onchange=()=>world.reduced=$('#motion').checked;
// Microphone is optional, temporary, and never part of progression.
let recorder=null,stream=null,recordURL=null,recordAudio=null,recordTimer=null,recordEpoch=0,recording=false;
function clearRecording(){recordEpoch++;clearTimeout(recordTimer);recording=false;if(recorder){recorder.ondataavailable=null;recorder.onstop=null;if(recorder.state!=='inactive')recorder.stop();recorder=null;}stream?.getTracks().forEach(t=>t.stop());stream=null;recordAudio?.pause();recordAudio=null;if(recordURL)URL.revokeObjectURL(recordURL);recordURL=null;show('#stop-record',false);show('#record');$('#record').disabled=false;$('#replay-record').disabled=true;}
$('#oral-open').onclick=()=>{closeModal('#finish');$('#oral-sentence').innerHTML=ruby(...phrases[0]);$('#oral-observe').value=data.chinese.oral;$('#oral-status').textContent='';openModal('#oral');};$('#oral-done').onclick=()=>{clearRecording();closeModal('#oral');openModal('#finish');};$('#oral-observe').onchange=()=>{data.chinese.oral=$('#oral-observe').value;save();};
$('#record').onclick=async()=>{clearRecording();const epoch=recordEpoch;$('#record').disabled=true;if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){$('#oral-status').textContent='这个浏览器暂不支持录音，直接读给家人听也很好。';$('#record').disabled=false;return;}try{const acquired=await navigator.mediaDevices.getUserMedia({audio:true});if(epoch!==recordEpoch||!$('#oral').open){acquired.getTracks().forEach(t=>t.stop());return;}stream=acquired;const parts=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>{if(e.data.size)parts.push(e.data);};recorder.onstop=()=>{if(epoch!==recordEpoch)return;stream?.getTracks().forEach(t=>t.stop());stream=null;recording=false;clearTimeout(recordTimer);recordURL=URL.createObjectURL(new Blob(parts,{type:recorder.mimeType||'audio/webm'}));$('#replay-record').disabled=false;show('#record');$('#record').disabled=false;show('#stop-record',false);$('#oral-status').textContent='读好了，可以听听自己。声音会在关闭这里时清除。';};recorder.start();recording=true;show('#record',false);show('#stop-record');$('#oral-status').textContent='正在录音，读一句就好（最多20秒）。';recordTimer=setTimeout(()=>{if(recorder?.state==='recording')recorder.stop();},20000);}catch{$('#oral-status').textContent='没能打开麦克风。可以直接读给家人听，不影响完成故事。';$('#record').disabled=false;clearRecording();}};
$('#stop-record').onclick=()=>{if(recorder?.state==='recording')recorder.stop();};$('#replay-record').onclick=()=>{if(recordURL){recordAudio?.pause();recordAudio=new Audio(recordURL);recordAudio.play().catch(()=>$('#oral-status').textContent='回听暂不可用，可以直接读给家人听。');}};
document.addEventListener('visibilitychange',()=>{active=!document.hidden;if(!active){speechSynthesis?.cancel();clearRecording();save();}if(world)world.paused=!active||!!document.querySelector('dialog[open]');});window.addEventListener('pagehide',()=>{clearRecording();save();});
try{world=new SpringWorld($('#world'),pick,dy=>{if(dy<0)release();});window.world=world;$('#motion').checked=world.reduced;await world.load(p=>{$('#load-progress').value=Math.round(p*100);$('#load-text').textContent=p>0?`小伙伴正在赶来… ${Math.round(p*100)}%`:'小伙伴正在赶来…';});show('#loading',false);home();window.ready=true;window.renderer=world.renderer;world.afterRender=()=>{const p=target?world.objectScreen(target):null;const cue=subject&&!busy&&!world.paused&&world.time-actionTime>9&&p?.visible;show('#target-mark',!!cue);if(cue){$('#target-mark').style.left=p.x+'px';$('#target-mark').style.top=p.y+'px';if(!hintedAt){tickRecord('hints');hintedAt=world.time;}}};}catch(e){show('#loading',false);show('#fatal');$('#fatal-text').textContent='请检查网络后再打开。如果设备不支持三维画面，可换用更新的 Safari 或浏览器。';console.error(e);}
setInterval(()=>{if(!world||!subject||world.paused||!active||data[subject].done)return;data[subject].seconds++;restElapsed++;if(++lastSave>=5){save();lastSave=0;}if(restElapsed>=480){restElapsed=0;openModal('#rest');}},1000);
window.gameStatus=()=>({subject,step,busy,scene:sceneKind,target,selected:[...selected],lit:[...lit],done:subject?data[subject].done:false,paused:world?.paused,records:JSON.parse(JSON.stringify(data)),targets:world?[...world.objects.keys()].map(id=>({id,...world.objectScreen(id)})):[]});
if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
